# Importações

In [1]:
import os
import random

import matplotlib.pyplot as plt
import numpy as np
import shap

from matplotlib.ticker import FuncFormatter
from sklearn.metrics import root_mean_squared_error
from sklearn.model_selection import TimeSeriesSplit
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import RandomForestRegressor as RF

import pandas as pd

SEED = 100
SEEDS = [1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000, 10000]
CAMPUS_TREINO = "PARANAGUÁ"
K_FOLDS = 4
N_CLASSES = 10


def reset_seed(rnd_seed=SEED):
    os.environ['PYTHONHASHSEED'] = '0'
    random.seed(rnd_seed)


def calcular_rrmse(y_true, y_pred):
    y_true = np.array(y_true)
    y_pred = np.array(y_pred)

    rmse = root_mean_squared_error(y_true, y_pred)

    mean_y_true = np.mean(y_true)

    rrmse = rmse / mean_y_true
    return rrmse


reset_seed()

/home/eduardo/miniconda3/envs/rapids-24.12/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

# Carregar Datasets

In [2]:
df = pd.read_csv("./dados/dados_mesclados.csv", sep=';', decimal='.')
df["DATA"] = pd.to_datetime(df["DATA"], format="%Y-%m-%d")
df

,CONSUMO,DATA,TEMP_MIN_MÉD_MENS,TEMP_MÉD_MIN_MENS,TEMP_MÉD_MÉD_MENS,TEMP_MÉD_MAX_MENS,TEMP_MÉD_ACC_MENS,TEMP_MAX_MÉD_MENS,PRECIPITAÇÃO_MÉD_MENS,TEMP_MIN_MIN_MENS,...,CURSOS_GRAD_VESPERTINO,CURSOS_GRAD_NOTURNO,CURSOS_POS,FÉRIAS,FERIADO,COVID,GREVE,CAMPUS,REGIÃO,ORDEM
0,11400.0,2015-02-28,18.0,22.0,25.0,27.0,692.0,33.0,4.0,18.0,...,0.0,1.428571,1.0,0,3,0,0,ASSIS CHATEAUBRIAND,REGIÃO OESTE,1
1,18427.0,2015-03-31,12.0,19.0,24.0,26.0,729.0,32.0,2.0,12.0,...,0.0,2.000000,1.0,0,0,0,0,ASSIS CHATEAUBRIAND,REGIÃO OESTE,2
2,14274.0,2015-04-30,13.0,19.0,21.0,24.0,640.0,29.0,6.0,13.0,...,0.0,2.000000,1.0,0,1,0,0,ASSIS CHATEAUBRIAND,REGIÃO OESTE,3
3,11987.0,2015-05-31,7.0,11.0,18.0,23.0,557.0,28.0,9.0,7.0,...,0.0,2.000000,1.0,0,0,0,0,ASSIS CHATEAUBRIAND,REGIÃO OESTE,4
4,9006.0,2015-06-30,4.0,10.0,18.0,22.0,542.0,29.0,1.0,4.0,...,0.0,2.000000,1.0,0,1,0,0,ASSIS CHATEAUBRIAND,REGIÃO OESTE,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2378,5640.0,2024-06-30,-0.0,8.0,17.0,20.0,499.0,26.0,1.0,-0.0,...,1.0,1.000000,0.0,0,0,0,30,UNIÃO DA VITÓRIA,REGIÃO SUL,81
2379,11687.0,2024-07-31,1.0,9.0,13.0,18.0,413.0,25.0,6.0,1.0,...,1.0,1.000000,0.0,12,0,0,0,UNIÃO DA VITÓRIA,REGIÃO SUL,82
2380,11129.0,2024-08-31,-3.0,7.0,15.0,21.0,468.0,31.0,1.0,-3.0,...,1.0,1.000000,0.0,0,0,0,0,UNIÃO DA VITÓRIA,REGIÃO SUL,83
2381,9690.0,2024-09-30,10.0,13.0,20.0,24.0,591.0,34.0,3.0,10.0,...,1.0,1.000000,0.0,0,0,0,0,UNIÃO DA VITÓRIA,REGIÃO SUL,84
2382,10416.0,2024-10-31,10.0,14.0,20.0,25.0,610.0,33.0,3.0,10.0,...,1.0,1.000000,0.0,0,0,0,0,UNIÃO DA VITÓRIA,REGIÃO SUL,85

# Tratamento dos dados
## Simplificação dos valores decimais

In [3]:
# Arredondamento dos dados, pelas casas decimais serem irrelevantes
df = df.round()

# Converte os dados para o tipo inteiro
df[df.drop(columns=["DATA", "CAMPUS", "REGIÃO"]).columns] = df[
    df.drop(columns=["DATA", "CAMPUS", "REGIÃO"]).columns].astype(int)

df

,CONSUMO,DATA,TEMP_MIN_MÉD_MENS,TEMP_MÉD_MIN_MENS,TEMP_MÉD_MÉD_MENS,TEMP_MÉD_MAX_MENS,TEMP_MÉD_ACC_MENS,TEMP_MAX_MÉD_MENS,PRECIPITAÇÃO_MÉD_MENS,TEMP_MIN_MIN_MENS,...,CURSOS_GRAD_VESPERTINO,CURSOS_GRAD_NOTURNO,CURSOS_POS,FÉRIAS,FERIADO,COVID,GREVE,CAMPUS,REGIÃO,ORDEM
0,11400,2015-02-28,18,22,25,27,692,33,4,18,...,0,1,1,0,3,0,0,ASSIS CHATEAUBRIAND,REGIÃO OESTE,1
1,18427,2015-03-31,12,19,24,26,729,32,2,12,...,0,2,1,0,0,0,0,ASSIS CHATEAUBRIAND,REGIÃO OESTE,2
2,14274,2015-04-30,13,19,21,24,640,29,6,13,...,0,2,1,0,1,0,0,ASSIS CHATEAUBRIAND,REGIÃO OESTE,3
3,11987,2015-05-31,7,11,18,23,557,28,9,7,...,0,2,1,0,0,0,0,ASSIS CHATEAUBRIAND,REGIÃO OESTE,4
4,9006,2015-06-30,4,10,18,22,542,29,1,4,...,0,2,1,0,1,0,0,ASSIS CHATEAUBRIAND,REGIÃO OESTE,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2378,5640,2024-06-30,0,8,17,20,499,26,1,0,...,1,1,0,0,0,0,30,UNIÃO DA VITÓRIA,REGIÃO SUL,81
2379,11687,2024-07-31,1,9,13,18,413,25,6,1,...,1,1,0,12,0,0,0,UNIÃO DA VITÓRIA,REGIÃO SUL,82
2380,11129,2024-08-31,-3,7,15,21,468,31,1,-3,...,1,1,0,0,0,0,0,UNIÃO DA VITÓRIA,REGIÃO SUL,83
2381,9690,2024-09-30,10,13,20,24,591,34,3,10,...,1,1,0,0,0,0,0,UNIÃO DA VITÓRIA,REGIÃO SUL,84
2382,10416,2024-10-31,10,14,20,25,610,33,3,10,...,1,1,0,0,0,0,0,UNIÃO DA VITÓRIA,REGIÃO SUL,85

## Remoção dos outliers

In [4]:
dataframes = []

for campus, dados in df.groupby("CAMPUS"):
    q1 = dados["CONSUMO"].quantile(0.25)
    q3 = dados["CONSUMO"].quantile(0.75)
    iqr = q3 - q1
    limite_inferior = q1 - 1.5 * iqr
    limite_superior = q3 + 1.5 * iqr

    dados["CONSUMO"] = np.where(dados["CONSUMO"] < limite_inferior, limite_inferior, dados["CONSUMO"])
    dados["CONSUMO"] = np.where(dados["CONSUMO"] > limite_superior, limite_superior, dados["CONSUMO"])

    dataframes.append(dados)

df = pd.concat(dataframes, ignore_index=True)
df.to_csv("./dados/dados_tratados.csv", index=False, sep=";", decimal=".")

df

,CONSUMO,DATA,TEMP_MIN_MÉD_MENS,TEMP_MÉD_MIN_MENS,TEMP_MÉD_MÉD_MENS,TEMP_MÉD_MAX_MENS,TEMP_MÉD_ACC_MENS,TEMP_MAX_MÉD_MENS,PRECIPITAÇÃO_MÉD_MENS,TEMP_MIN_MIN_MENS,...,CURSOS_GRAD_VESPERTINO,CURSOS_GRAD_NOTURNO,CURSOS_POS,FÉRIAS,FERIADO,COVID,GREVE,CAMPUS,REGIÃO,ORDEM
0,11400.0,2015-02-28,18,22,25,27,692,33,4,18,...,0,1,1,0,3,0,0,ASSIS CHATEAUBRIAND,REGIÃO OESTE,1
1,18427.0,2015-03-31,12,19,24,26,729,32,2,12,...,0,2,1,0,0,0,0,ASSIS CHATEAUBRIAND,REGIÃO OESTE,2
2,14274.0,2015-04-30,13,19,21,24,640,29,6,13,...,0,2,1,0,1,0,0,ASSIS CHATEAUBRIAND,REGIÃO OESTE,3
3,11987.0,2015-05-31,7,11,18,23,557,28,9,7,...,0,2,1,0,0,0,0,ASSIS CHATEAUBRIAND,REGIÃO OESTE,4
4,9006.0,2015-06-30,4,10,18,22,542,29,1,4,...,0,2,1,0,1,0,0,ASSIS CHATEAUBRIAND,REGIÃO OESTE,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2378,5640.0,2024-06-30,0,8,17,20,499,26,1,0,...,1,1,0,0,0,0,30,UNIÃO DA VITÓRIA,REGIÃO SUL,81
2379,11687.0,2024-07-31,1,9,13,18,413,25,6,1,...,1,1,0,12,0,0,0,UNIÃO DA VITÓRIA,REGIÃO SUL,82
2380,11129.0,2024-08-31,-3,7,15,21,468,31,1,-3,...,1,1,0,0,0,0,0,UNIÃO DA VITÓRIA,REGIÃO SUL,83
2381,9690.0,2024-09-30,10,13,20,24,591,34,3,10,...,1,1,0,0,0,0,0,UNIÃO DA VITÓRIA,REGIÃO SUL,84
2382,10416.0,2024-10-31,10,14,20,25,610,33,3,10,...,1,1,0,0,0,0,0,UNIÃO DA VITÓRIA,REGIÃO SUL,85

# Normalização

In [5]:
dataframes = []

for campus, dados in df.groupby("CAMPUS"):
    scaler = MinMaxScaler()
    dados[["CONSUMO"]] = scaler.fit_transform(dados[["CONSUMO"]]).round(
        15)  # Reduz a precisão para evitar problemas de ultrapassagem da escala 1
    dataframes.append(dados)

df_normalizado = pd.concat(dataframes, ignore_index=True)
df_normalizado.to_csv("./dados/dados_normalizados.csv", index=False, sep=";", decimal=".")

df_normalizado

,CONSUMO,DATA,TEMP_MIN_MÉD_MENS,TEMP_MÉD_MIN_MENS,TEMP_MÉD_MÉD_MENS,TEMP_MÉD_MAX_MENS,TEMP_MÉD_ACC_MENS,TEMP_MAX_MÉD_MENS,PRECIPITAÇÃO_MÉD_MENS,TEMP_MIN_MIN_MENS,...,CURSOS_GRAD_VESPERTINO,CURSOS_GRAD_NOTURNO,CURSOS_POS,FÉRIAS,FERIADO,COVID,GREVE,CAMPUS,REGIÃO,ORDEM
0,0.502037,2015-02-28,18,22,25,27,692,33,4,18,...,0,1,1,0,3,0,0,ASSIS CHATEAUBRIAND,REGIÃO OESTE,1
1,0.846886,2015-03-31,12,19,24,26,729,32,2,12,...,0,2,1,0,0,0,0,ASSIS CHATEAUBRIAND,REGIÃO OESTE,2
2,0.643078,2015-04-30,13,19,21,24,640,29,6,13,...,0,2,1,0,1,0,0,ASSIS CHATEAUBRIAND,REGIÃO OESTE,3
3,0.530844,2015-05-31,7,11,18,23,557,28,9,7,...,0,2,1,0,0,0,0,ASSIS CHATEAUBRIAND,REGIÃO OESTE,4
4,0.384551,2015-06-30,4,10,18,22,542,29,1,4,...,0,2,1,0,1,0,0,ASSIS CHATEAUBRIAND,REGIÃO OESTE,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2378,0.359224,2024-06-30,0,8,17,20,499,26,1,0,...,1,1,0,0,0,0,30,UNIÃO DA VITÓRIA,REGIÃO SUL,81
2379,1.000000,2024-07-31,1,9,13,18,413,25,6,1,...,1,1,0,12,0,0,0,UNIÃO DA VITÓRIA,REGIÃO SUL,82
2380,0.940871,2024-08-31,-3,7,15,21,468,31,1,-3,...,1,1,0,0,0,0,0,UNIÃO DA VITÓRIA,REGIÃO SUL,83
2381,0.788386,2024-09-30,10,13,20,24,591,34,3,10,...,1,1,0,0,0,0,0,UNIÃO DA VITÓRIA,REGIÃO SUL,84
2382,0.865317,2024-10-31,10,14,20,25,610,33,3,10,...,1,1,0,0,0,0,0,UNIÃO DA VITÓRIA,REGIÃO SUL,85

# Criação das Classes

In [6]:
def formater_thousands(x, pos):
    return f'{x:.2f}'.replace('.', ',')


def mapear_classe(consumo, intervalos_quantils):
    for i, (inicio_intervalo, fim_intervalo) in enumerate(intervalos_quantils):
        if inicio_intervalo <= consumo <= fim_intervalo:
            return i


df_classes = df_normalizado.copy()
quantiles = np.linspace(0, 1, N_CLASSES + 1)
intervalos = df_classes["CONSUMO"].quantile(quantiles).to_numpy()

classes = [[intervalos[i], intervalos[i + 1]] for i in range(len(intervalos) - 1)]
df_classes["CLASSE"] = df_classes["CONSUMO"].apply(lambda val: mapear_classe(val, classes)).astype(int)
df_classes.to_csv(f"./dados/{N_CLASSES}_classes_normalizadas.csv", index=False, sep=";", decimal=".")
df_classes

,CONSUMO,DATA,TEMP_MIN_MÉD_MENS,TEMP_MÉD_MIN_MENS,TEMP_MÉD_MÉD_MENS,TEMP_MÉD_MAX_MENS,TEMP_MÉD_ACC_MENS,TEMP_MAX_MÉD_MENS,PRECIPITAÇÃO_MÉD_MENS,TEMP_MIN_MIN_MENS,...,CURSOS_GRAD_NOTURNO,CURSOS_POS,FÉRIAS,FERIADO,COVID,GREVE,CAMPUS,REGIÃO,ORDEM,CLASSE
0,0.502037,2015-02-28,18,22,25,27,692,33,4,18,...,1,1,0,3,0,0,ASSIS CHATEAUBRIAND,REGIÃO OESTE,1,6
1,0.846886,2015-03-31,12,19,24,26,729,32,2,12,...,2,1,0,0,0,0,ASSIS CHATEAUBRIAND,REGIÃO OESTE,2,9
2,0.643078,2015-04-30,13,19,21,24,640,29,6,13,...,2,1,0,1,0,0,ASSIS CHATEAUBRIAND,REGIÃO OESTE,3,8
3,0.530844,2015-05-31,7,11,18,23,557,28,9,7,...,2,1,0,0,0,0,ASSIS CHATEAUBRIAND,REGIÃO OESTE,4,6
4,0.384551,2015-06-30,4,10,18,22,542,29,1,4,...,2,1,0,1,0,0,ASSIS CHATEAUBRIAND,REGIÃO OESTE,5,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2378,0.359224,2024-06-30,0,8,17,20,499,26,1,0,...,1,0,0,0,0,30,UNIÃO DA VITÓRIA,REGIÃO SUL,81,3
2379,1.000000,2024-07-31,1,9,13,18,413,25,6,1,...,1,0,12,0,0,0,UNIÃO DA VITÓRIA,REGIÃO SUL,82,9
2380,0.940871,2024-08-31,-3,7,15,21,468,31,1,-3,...,1,0,0,0,0,0,UNIÃO DA VITÓRIA,REGIÃO SUL,83,9
2381,0.788386,2024-09-30,10,13,20,24,591,34,3,10,...,1,0,0,0,0,0,UNIÃO DA VITÓRIA,REGIÃO SUL,84,9
2382,0.865317,2024-10-31,10,14,20,25,610,33,3,10,...,1,0,0,0,0,0,UNIÃO DA VITÓRIA,REGIÃO SUL,85,9

## Análise das Classes

In [7]:
def plot_classes(dados, campus, plot_serie=True):
    plt.figure(figsize=(18, 5))
    plt.rcParams['xtick.labelsize'] = 15
    plt.rcParams['ytick.labelsize'] = 15
    plt.rcParams.update({'font.size': 15})

    for i, (inicio, fim) in enumerate(classes):
        plt.fill_between(
            dados["DATA"],
            inicio,
            fim,
            alpha=0.65,
            label=f"Classe {i} ({inicio:.5f} - {fim:.5f})"
        )
    if plot_serie:
        plt.plot(dados["DATA"], dados["CONSUMO"], label="Consumo", color="black")

    plt.xlabel('MESES')
    plt.ylabel('CONSUMO NORMALIZADO')

    ax = plt.gca()
    ax.yaxis.set_major_formatter(FuncFormatter(formater_thousands))
    ax.set_facecolor('white')
    plt.grid(True, color='white', linestyle="--", linewidth=0.75)
    plt.legend(facecolor='white', framealpha=0.5, bbox_to_anchor=(1.05, 1))
    plt.savefig(f"./dados/classes/{N_CLASSES} Classes {campus}.png", bbox_inches='tight')
    plt.close()


def plot_distribuicao_classes(dados, campus):
    distribuicao_classes = dados["CLASSE"].value_counts()

    plt.figure(figsize=(12, 6))
    bars = plt.bar(distribuicao_classes.index, distribuicao_classes.values, color="blue", alpha=0.8)

    for bar in bars:
        altura = bar.get_height()
        plt.text(bar.get_x() + bar.get_width() / 2, altura / 2, f"{int(altura)}",
                 ha="center", va="center", fontsize=12, color="white")

    plt.xlabel("CLASSE", fontsize=14)
    plt.ylabel("QUANTIDADE DE DADOS", fontsize=14)
    plt.xticks(df_classes["CLASSE"].unique(), fontsize=12)
    plt.yticks(fontsize=12)
    plt.grid(axis="y", linestyle="--", alpha=0.7)

    plt.savefig(f"./dados/classes/Distribuição {N_CLASSES} Classes {campus}.png", bbox_inches="tight")
    plt.close()


for campus, dados in df_classes.groupby("CAMPUS"):
    plot_classes(dados, campus)
    plot_distribuicao_classes(dados, campus)

plot_classes(df_classes, "_TODOS", False)
plot_distribuicao_classes(df_classes, "_TODOS_")

# Criação dos Lags
## Regressão

In [8]:
dataframes = []

for campus, dados in df_normalizado.sort_values("DATA").groupby("CAMPUS"):
    lags = {f'LAG_{i:02d}': dados['CONSUMO'].shift(i) for i in range(1, 12 + 1)}
    dados = pd.concat([dados, pd.DataFrame(lags)], axis=1)
    dados = dados.dropna()
    dados["ORDEM"] = range(1, len(dados) + 1)
    dataframes.append(dados)

df_normalizado = pd.concat(dataframes, ignore_index=True)
df_normalizado.to_csv("./dados/dados_normalizados_lagados.csv", index=False, sep=";", decimal=".")
df_normalizado

,CONSUMO,DATA,TEMP_MIN_MÉD_MENS,TEMP_MÉD_MIN_MENS,TEMP_MÉD_MÉD_MENS,TEMP_MÉD_MAX_MENS,TEMP_MÉD_ACC_MENS,TEMP_MAX_MÉD_MENS,PRECIPITAÇÃO_MÉD_MENS,TEMP_MIN_MIN_MENS,...,LAG_03,LAG_04,LAG_05,LAG_06,LAG_07,LAG_08,LAG_09,LAG_10,LAG_11,LAG_12
0,0.615105,2016-02-29,19,22,25,28,734,33,4,19,...,0.570938,0.553762,0.386907,0.331354,0.302547,0.384551,0.530844,0.643078,0.846886,0.502037
1,0.711047,2016-03-31,12,17,22,28,685,32,3,12,...,0.580507,0.570938,0.553762,0.386907,0.331354,0.302547,0.384551,0.530844,0.643078,0.846886
2,0.633361,2016-04-30,4,9,23,28,702,33,2,4,...,0.424204,0.580507,0.570938,0.553762,0.386907,0.331354,0.302547,0.384551,0.530844,0.643078
3,0.406291,2016-05-31,4,11,16,22,490,27,9,4,...,0.615105,0.424204,0.580507,0.570938,0.553762,0.386907,0.331354,0.302547,0.384551,0.530844
4,0.362467,2016-06-30,-1,7,14,20,408,27,3,-1,...,0.711047,0.615105,0.424204,0.580507,0.570938,0.553762,0.386907,0.331354,0.302547,0.384551
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2090,0.359224,2024-06-30,0,8,17,20,499,26,1,0,...,0.990145,0.803327,0.457985,0.822613,0.794744,0.559818,0.747059,0.839038,0.553248,0.743880
2091,1.000000,2024-07-31,1,9,13,18,413,25,6,1,...,0.680301,0.990145,0.803327,0.457985,0.822613,0.794744,0.559818,0.747059,0.839038,0.553248
2092,0.940871,2024-08-31,-3,7,15,21,468,31,1,-3,...,0.352866,0.680301,0.990145,0.803327,0.457985,0.822613,0.794744,0.559818,0.747059,0.839038
2093,0.788386,2024-09-30,10,13,20,24,591,34,3,10,...,0.359224,0.352866,0.680301,0.990145,0.803327,0.457985,0.822613,0.794744,0.559818,0.747059
2094,0.865317,2024-10-31,10,14,20,25,610,33,3,10,...,1.000000,0.359224,0.352866,0.680301,0.990145,0.803327,0.457985,0.822613,0.794744,0.559818

## Classificação

In [9]:
dataframes = []

for campus, dados in df_classes.sort_values("DATA").groupby("CAMPUS"):
    lags = {f'LAG_{i:02d}': dados['CLASSE'].shift(i) for i in range(1, 12 + 1)}
    dados = pd.concat([dados, pd.DataFrame(lags)], axis=1)
    dados = dados.dropna()
    dados[list(lags.keys())] = dados[list(lags.keys())].astype(int)  # Converte os lags para int
    dados["ORDEM"] = range(1, len(dados) + 1)
    dataframes.append(dados)

df_classes = pd.concat(dataframes, ignore_index=True)
df_classes.to_csv(f"./dados/{N_CLASSES}_classes_normalizadas_lagadas.csv", index=False, sep=";", decimal=".")

df_classes

,CONSUMO,DATA,TEMP_MIN_MÉD_MENS,TEMP_MÉD_MIN_MENS,TEMP_MÉD_MÉD_MENS,TEMP_MÉD_MAX_MENS,TEMP_MÉD_ACC_MENS,TEMP_MAX_MÉD_MENS,PRECIPITAÇÃO_MÉD_MENS,TEMP_MIN_MIN_MENS,...,LAG_03,LAG_04,LAG_05,LAG_06,LAG_07,LAG_08,LAG_09,LAG_10,LAG_11,LAG_12
0,0.615105,2016-02-29,19,22,25,28,734,33,4,19,...,7,7,4,3,3,4,6,8,9,6
1,0.711047,2016-03-31,12,17,22,28,685,32,3,12,...,7,7,7,4,3,3,4,6,8,9
2,0.633361,2016-04-30,4,9,23,28,702,33,2,4,...,4,7,7,7,4,3,3,4,6,8
3,0.406291,2016-05-31,4,11,16,22,490,27,9,4,...,7,4,7,7,7,4,3,3,4,6
4,0.362467,2016-06-30,-1,7,14,20,408,27,3,-1,...,8,7,4,7,7,7,4,3,3,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2090,0.359224,2024-06-30,0,8,17,20,499,26,1,0,...,9,9,5,9,9,7,8,9,7,8
2091,1.000000,2024-07-31,1,9,13,18,413,25,6,1,...,8,9,9,5,9,9,7,8,9,7
2092,0.940871,2024-08-31,-3,7,15,21,468,31,1,-3,...,3,8,9,9,5,9,9,7,8,9
2093,0.788386,2024-09-30,10,13,20,24,591,34,3,10,...,3,3,8,9,9,5,9,9,7,8
2094,0.865317,2024-10-31,10,14,20,25,610,33,3,10,...,9,3,3,8,9,9,5,9,9,7

# Importância das Features

In [ ]:
shap.initjs()

def calcular_importancia(dados):
    x = dados.drop(columns=["CONSUMO", "DATA", "CAMPUS", "REGIÃO"])
    y = dados["CONSUMO"]

    rf = RF(random_state=SEED)
    rf.fit(x, y)

    explainer_rf = shap.explainers.TreeExplainer(rf)

    shap_rf = explainer_rf(x)
    importancia = pd.DataFrame(list(zip(x.columns, np.abs(shap_rf.values).mean(0))), columns=["FEATURE", "IMPORTÂNCIA"])
    importancia["IMPORTÂNCIA"] = importancia["IMPORTÂNCIA"].round(15)
    importancia = importancia.sort_values(by="FEATURE")
    importancia = importancia.set_index("FEATURE")
    return importancia


# Calcula a importância individual de cada campus
importancias = pd.DataFrame(index=pd.Index(df_normalizado.drop(columns=["CONSUMO", "DATA", "CAMPUS", "REGIÃO"]).columns, name="FEATURE"))
for campus, dados in df_normalizado.groupby("CAMPUS"):
    importancias[[campus]] = calcular_importancia(dados)[["IMPORTÂNCIA"]]

# Calcula a importância geral de todos os campus
importancias[["_TODOS_"]] = calcular_importancia(df_normalizado)[["IMPORTÂNCIA"]]

# Calcula a média das importâncias
importancias["MÉDIA"] = importancias.mean(axis=1)
importancias = importancias.sort_values(by=["MÉDIA"], ascending=False)
importancias.to_csv("./resultados/features/importancia_regressao.csv", index=True, sep=";", decimal=".")

importancias

# Remoção de Features

In [10]:
importancias = pd.read_csv("./resultados/features/importancia_regressao.csv", sep=";", decimal=".", header=0)

features_selecao = importancias.copy()
features_selecao['PERCENTUAL'] = features_selecao['MÉDIA'] / features_selecao['MÉDIA'].sum()

# Remove as features com importância 0
features_selecao = features_selecao[features_selecao["PERCENTUAL"] > 0]

# Seleciona as features com importância percentual menor que 1% para serem sorteadas
features_sorteio = features_selecao[features_selecao["PERCENTUAL"] < 0.01].copy()

features_sorteio["PERCENTUAL"] = 1 - features_sorteio["PERCENTUAL"]
features_sorteio["PROBABILIDADE"] = features_sorteio["PERCENTUAL"] / features_sorteio["PERCENTUAL"].sum()

fitness_regressao = {}

for seed in SEEDS:
    reset_seed(seed)
    for i in range(0, 100):
        print(f"SEED: {seed} - Iter {i}")
        rf = RF(random_state=SEED)

        # Remove features com menor importância
        opt_features = np.random.choice(
            features_sorteio['FEATURE'],
            size=np.random.randint(int(len(features_sorteio)/2), len(features_sorteio)), # Seleciona um número aleatório de features
            replace=False, # Impede a repetição de features na seleção
            p=features_sorteio['PROBABILIDADE']
        ).tolist() + ["CONSUMO", "DATA", "CAMPUS", "REGIÃO"]

        # Treinamento com apenas o campus com a maior quantidade de dados
        dataset_treino = df_normalizado[df_normalizado["CAMPUS"] == CAMPUS_TREINO]
        cvs = []
        for i_treino, i_teste in TimeSeriesSplit(n_splits=K_FOLDS, test_size=1).split(dataset_treino):
            x_treino = df_normalizado.drop(columns=opt_features).iloc[i_treino]
            y_treino = df_normalizado["CONSUMO"].iloc[i_treino]
            # Teste com os dados de todos os campus
            data_teste = dataset_treino.iloc[i_teste]["DATA"].values[0]
            df_teste = df_normalizado.loc[df_normalizado["DATA"] == data_teste]
            x_teste = df_teste.drop(columns=opt_features)
            y_teste = df_teste["CONSUMO"]

            y_previsto = []
            rf.fit(x_treino, y_treino)
            for _, row in x_teste.iterrows():
                previsao = rf.predict(pd.DataFrame([row.values], columns=x_teste.columns))[0]
                y_previsto.append(previsao)
            erros = calcular_rrmse(y_teste, y_previsto)
            cvs.append(erros.mean())

        print("RRMSE:", np.array(cvs).mean())
        fitness_regressao[tuple(dataset_treino.drop(columns=opt_features).columns.to_list())] = np.array(cvs).mean().round(5)

fitness_regressao = pd.DataFrame(list(fitness_regressao.items()), columns=["FEATURES", "RRMSE"])
fitness_regressao.to_csv("./resultados/features/fitness_features_regressao.csv", index=False, sep=";", decimal=".")
fitness_regressao

SEED: 1000 - Iter 0
RRMSE: 0.35920811347261195
SEED: 1000 - Iter 1
RRMSE: 0.3628986321942949
SEED: 1000 - Iter 2
RRMSE: 0.3667823433422729
SEED: 1000 - Iter 3
RRMSE: 0.3651061454139495
SEED: 1000 - Iter 4
RRMSE: 0.3589200505156557
SEED: 1000 - Iter 5
RRMSE: 0.3614157311111169
SEED: 1000 - Iter 6
RRMSE: 0.3612832395487323
SEED: 1000 - Iter 7
RRMSE: 0.3615181981640747
SEED: 1000 - Iter 8
RRMSE: 0.36613843762069254
SEED: 1000 - Iter 9
RRMSE: 0.35862503449491767
SEED: 1000 - Iter 10
RRMSE: 0.3579562422624928
SEED: 1000 - Iter 11
RRMSE: 0.35870138587704326
SEED: 1000 - Iter 12
RRMSE: 0.35445660687395475
SEED: 1000 - Iter 13
RRMSE: 0.3671717652499816
SEED: 1000 - Iter 14
RRMSE: 0.36681644158675963
SEED: 1000 - Iter 15
RRMSE: 0.36131762476322177
SEED: 1000 - Iter 16
RRMSE: 0.36271977636829567
SEED: 1000 - Iter 17
RRMSE: 0.36310350675629277
SEED: 1000 - Iter 18
RRMSE: 0.361148021652012
SEED: 1000 - Iter 19
RRMSE: 0.35649197289602974
SEED: 1000 - Iter 20
RRMSE: 0.3639422019455464
SEED: 1000 - Iter 21
RRMSE: 0.36836312429757145
SEED: 1000 - Iter 22
RRMSE: 0.35620590562933846
SEED: 1000 - Iter 23
RRMSE: 0.35533980299661505
SEED: 1000 - Iter 24
RRMSE: 0.37204173200182244
SEED: 1000 - Iter 25
RRMSE: 0.3636802688028122
SEED: 1000 - Iter 26
RRMSE: 0.35727184182466765
SEED: 1000 - Iter 27
RRMSE: 0.35727526808914833
SEED: 1000 - Iter 28
RRMSE: 0.37022730821708116
SEED: 1000 - Iter 29
RRMSE: 0.35870138587704326
SEED: 1000 - Iter 30
RRMSE: 0.35768472328719125
SEED: 1000 - Iter 31
RRMSE: 0.36684543363354694
SEED: 1000 - Iter 32
RRMSE: 0.36433534316253074
SEED: 1000 - Iter 33
RRMSE: 0.35656693244158927
SEED: 1000 - Iter 34
RRMSE: 0.3622533638629339
SEED: 1000 - Iter 35
RRMSE: 0.3587651616807721
SEED: 1000 - Iter 36
RRMSE: 0.3632836147655115
SEED: 1000 - Iter 37
RRMSE: 0.36262924398868734
SEED: 1000 - Iter 38
RRMSE: 0.36627458349699843
SEED: 1000 - Iter 39
RRMSE: 0.36196792114419885
SEED: 1000 - Iter 40
RRMSE: 0.3722530193389214
SEED: 1000 - Iter 41
RRMSE: 0.3571243457548243
SEED: 1000 - Iter 42
RRMSE: 0.37560494051870574
SEED: 1000 - Iter 43
RRMSE: 0.37335496469762064
SEED: 1000 - Iter 44
RRMSE: 0.36976255299365324
SEED: 1000 - Iter 45
RRMSE: 0.3605747486635565
SEED: 1000 - Iter 46
RRMSE: 0.36816606264754853
SEED: 1000 - Iter 47
RRMSE: 0.3676956898875475
SEED: 1000 - Iter 48
RRMSE: 0.36669552346223544
SEED: 1000 - Iter 49
RRMSE: 0.36417277596779546
SEED: 1000 - Iter 50
RRMSE: 0.3595992553714813
SEED: 1000 - Iter 51
RRMSE: 0.35459919961584796
SEED: 1000 - Iter 52
RRMSE: 0.3622056364821458
SEED: 1000 - Iter 53
RRMSE: 0.36576094684741445
SEED: 1000 - Iter 54
RRMSE: 0.36105499791109963
SEED: 1000 - Iter 55
RRMSE: 0.3608197140040755
SEED: 1000 - Iter 56
RRMSE: 0.36483526419937273
SEED: 1000 - Iter 57
RRMSE: 0.3598030139826289
SEED: 1000 - Iter 58
RRMSE: 0.3633131359320295
SEED: 1000 - Iter 59
RRMSE: 0.3574377121687284
SEED: 1000 - Iter 60
RRMSE: 0.3673720469045635
SEED: 1000 - Iter 61
RRMSE: 0.36869016238335955
SEED: 1000 - Iter 62
RRMSE: 0.3623341048594805
SEED: 1000 - Iter 63
RRMSE: 0.36153143491050954
SEED: 1000 - Iter 64
RRMSE: 0.36729798393972457
SEED: 1000 - Iter 65
RRMSE: 0.36204548754510096
SEED: 1000 - Iter 66
RRMSE: 0.36073264093503127
SEED: 1000 - Iter 67
RRMSE: 0.3646028459705005
SEED: 1000 - Iter 68
RRMSE: 0.3651278191410571
SEED: 1000 - Iter 69
RRMSE: 0.35610165467837596
SEED: 1000 - Iter 70
RRMSE: 0.3601361415789881
SEED: 1000 - Iter 71
RRMSE: 0.365190167555895
SEED: 1000 - Iter 72
RRMSE: 0.36409703302358487
SEED: 1000 - Iter 73
RRMSE: 0.35977422987155594
SEED: 1000 - Iter 74
RRMSE: 0.3638356095876673
SEED: 1000 - Iter 75
RRMSE: 0.35666557134548277
SEED: 1000 - Iter 76
RRMSE: 0.3696532474288292
SEED: 1000 - Iter 77
RRMSE: 0.3631888641164174
SEED: 1000 - Iter 78
RRMSE: 0.37103455505484456
SEED: 1000 - Iter 79
RRMSE: 0.36188225349670333
SEED: 1000 - Iter 80
RRMSE: 0.3571838088502002
SEED: 1000 - Iter 81
RRMSE: 0.3659844397804485
SEED: 1000 - Iter 82
RRMSE: 0.35830713295035593
SEED: 1000 - Iter 83
RRMSE: 0.3548784695729696
SEED: 1000 - Iter 84
RRMSE: 0.35870138587704326
SEED: 1000 - Iter 85
RRMSE: 0.3589098762979881
SEED: 1000 - Iter 86
RRMSE: 0.3626337721513688
SEED: 1000 - Iter 87
RRMSE: 0.3678376396789657
SEED: 1000 - Iter 88
RRMSE: 0.3608024727052651
SEED: 1000 - Iter 89
RRMSE: 0.3659887183495586
SEED: 1000 - Iter 90
RRMSE: 0.36384033753356876
SEED: 1000 - Iter 91
RRMSE: 0.3626752190776807
SEED: 1000 - Iter 92
RRMSE: 0.36667322190799506
SEED: 1000 - Iter 93
RRMSE: 0.3622696986727707
SEED: 1000 - Iter 94
RRMSE: 0.357371747468585
SEED: 1000 - Iter 95
RRMSE: 0.3529113801429136
SEED: 1000 - Iter 96
RRMSE: 0.36376263049304114
SEED: 1000 - Iter 97
RRMSE: 0.3726386609681761
SEED: 1000 - Iter 98
RRMSE: 0.35983747902198715
SEED: 1000 - Iter 99
RRMSE: 0.361502926625841
SEED: 2000 - Iter 0
RRMSE: 0.364702125073337
SEED: 2000 - Iter 1
RRMSE: 0.3694740227247683
SEED: 2000 - Iter 2
RRMSE: 0.3637339463635863
SEED: 2000 - Iter 3
RRMSE: 0.3613313858643233
SEED: 2000 - Iter 4
RRMSE: 0.36814584004389395
SEED: 2000 - Iter 5
RRMSE: 0.36781526159030253
SEED: 2000 - Iter 6
RRMSE: 0.36124697614739953
SEED: 2000 - Iter 7
RRMSE: 0.3629155776973779
SEED: 2000 - Iter 8
RRMSE: 0.3685101237883479
SEED: 2000 - Iter 9
RRMSE: 0.36355616132601964
SEED: 2000 - Iter 10
RRMSE: 0.36449942230583654
SEED: 2000 - Iter 11
RRMSE: 0.36347822672651126
SEED: 2000 - Iter 12
RRMSE: 0.37492310582383837
SEED: 2000 - Iter 13
RRMSE: 0.3618431852516956
SEED: 2000 - Iter 14
RRMSE: 0.37717755132324626
SEED: 2000 - Iter 15
RRMSE: 0.361862391273082
SEED: 2000 - Iter 16
RRMSE: 0.3617203413281157
SEED: 2000 - Iter 17
RRMSE: 0.3691440076558652
SEED: 2000 - Iter 18
RRMSE: 0.360599623031605
SEED: 2000 - Iter 19
RRMSE: 0.3673082192672375
SEED: 2000 - Iter 20
RRMSE: 0.3691431273149266
SEED: 2000 - Iter 21
RRMSE: 0.36716815842203954
SEED: 2000 - Iter 22
RRMSE: 0.36454246553075575
SEED: 2000 - Iter 23
RRMSE: 0.36256306529187277
SEED: 2000 - Iter 24
RRMSE: 0.36887629713846143
SEED: 2000 - Iter 25
RRMSE: 0.35998896071732983
SEED: 2000 - Iter 26
RRMSE: 0.36358687189106276
SEED: 2000 - Iter 27
RRMSE: 0.3606039820066102
SEED: 2000 - Iter 28
RRMSE: 0.36618030811586827
SEED: 2000 - Iter 29
RRMSE: 0.3633126169526645
SEED: 2000 - Iter 30
RRMSE: 0.3589630140783744
SEED: 2000 - Iter 31
RRMSE: 0.3685313016675347
SEED: 2000 - Iter 32
RRMSE: 0.36041364456328784
SEED: 2000 - Iter 33
RRMSE: 0.35964001431821846
SEED: 2000 - Iter 34
RRMSE: 0.3606681571968454
SEED: 2000 - Iter 35
RRMSE: 0.36997988581327923
SEED: 2000 - Iter 36
RRMSE: 0.36230157112856104
SEED: 2000 - Iter 37
RRMSE: 0.36517501143871434
SEED: 2000 - Iter 38
RRMSE: 0.3671030002150477
SEED: 2000 - Iter 39
RRMSE: 0.3629737346789592
SEED: 2000 - Iter 40
RRMSE: 0.3657088851910753
SEED: 2000 - Iter 41
RRMSE: 0.35919547905426885
SEED: 2000 - Iter 42
RRMSE: 0.3605491864847503
SEED: 2000 - Iter 43
RRMSE: 0.36781947447182495
SEED: 2000 - Iter 44
RRMSE: 0.36455826914635964
SEED: 2000 - Iter 45
RRMSE: 0.36702519145178875
SEED: 2000 - Iter 46
RRMSE: 0.364817143501199
SEED: 2000 - Iter 47
RRMSE: 0.36636107137115664
SEED: 2000 - Iter 48
RRMSE: 0.3575729673264318
SEED: 2000 - Iter 49
RRMSE: 0.36161665920447117
SEED: 2000 - Iter 50
RRMSE: 0.36572068840220645
SEED: 2000 - Iter 51
RRMSE: 0.362899042926141
SEED: 2000 - Iter 52
RRMSE: 0.3732202905723596
SEED: 2000 - Iter 53
RRMSE: 0.3576718163519012
SEED: 2000 - Iter 54
RRMSE: 0.35532672303405655
SEED: 2000 - Iter 55
RRMSE: 0.36250361950205345
SEED: 2000 - Iter 56
RRMSE: 0.3637130816353915
SEED: 2000 - Iter 57
RRMSE: 0.36524431304967403
SEED: 2000 - Iter 58
RRMSE: 0.364369703394794
SEED: 2000 - Iter 59
RRMSE: 0.37011557724013905
SEED: 2000 - Iter 60
RRMSE: 0.36090709535381904
SEED: 2000 - Iter 61
RRMSE: 0.3543079325817135
SEED: 2000 - Iter 62
RRMSE: 0.36450541171601
SEED: 2000 - Iter 63
RRMSE: 0.35349337799976366
SEED: 2000 - Iter 64
RRMSE: 0.3703516034601381
SEED: 2000 - Iter 65
RRMSE: 0.36269625132297817
SEED: 2000 - Iter 66
RRMSE: 0.36384652648334115
SEED: 2000 - Iter 67
RRMSE: 0.3625052358940846
SEED: 2000 - Iter 68
RRMSE: 0.36157595431320755
SEED: 2000 - Iter 69
RRMSE: 0.3698320016122132
SEED: 2000 - Iter 70
RRMSE: 0.36628249693709347
SEED: 2000 - Iter 71
RRMSE: 0.3588039545272243
SEED: 2000 - Iter 72
RRMSE: 0.3652778986737232
SEED: 2000 - Iter 73
RRMSE: 0.3626759558624839
SEED: 2000 - Iter 74
RRMSE: 0.3730329009842672
SEED: 2000 - Iter 75
RRMSE: 0.36598491243343434
SEED: 2000 - Iter 76
RRMSE: 0.3664660166342121
SEED: 2000 - Iter 77
RRMSE: 0.37155835364305956
SEED: 2000 - Iter 78
RRMSE: 0.35870138587704326
SEED: 2000 - Iter 79
RRMSE: 0.3673257728357753
SEED: 2000 - Iter 80
RRMSE: 0.37102989490463556
SEED: 2000 - Iter 81
RRMSE: 0.36862300930171865
SEED: 2000 - Iter 82
RRMSE: 0.36449896464183745
SEED: 2000 - Iter 83
RRMSE: 0.3617726193231834
SEED: 2000 - Iter 84
RRMSE: 0.36361342794422397
SEED: 2000 - Iter 85
RRMSE: 0.3617348935703041
SEED: 2000 - Iter 86
RRMSE: 0.3690669920803876
SEED: 2000 - Iter 87
RRMSE: 0.374250076560392
SEED: 2000 - Iter 88
RRMSE: 0.3608228443278828
SEED: 2000 - Iter 89
RRMSE: 0.3659644537911126
SEED: 2000 - Iter 90
RRMSE: 0.36642753611827494
SEED: 2000 - Iter 91
RRMSE: 0.3654269694313936
SEED: 2000 - Iter 92
RRMSE: 0.36099443186741326
SEED: 2000 - Iter 93
RRMSE: 0.3641581299692341
SEED: 2000 - Iter 94
RRMSE: 0.3643978902148344
SEED: 2000 - Iter 95
RRMSE: 0.35870138587704326
SEED: 2000 - Iter 96
RRMSE: 0.3540826601608134
SEED: 2000 - Iter 97
RRMSE: 0.36091755774280554
SEED: 2000 - Iter 98
RRMSE: 0.3624572675777797
SEED: 2000 - Iter 99
RRMSE: 0.36945964223647887
SEED: 3000 - Iter 0
RRMSE: 0.3634289950266406
SEED: 3000 - Iter 1
RRMSE: 0.35796112550339865
SEED: 3000 - Iter 2
RRMSE: 0.3615888624122238
SEED: 3000 - Iter 3
RRMSE: 0.3611608881148379
SEED: 3000 - Iter 4
RRMSE: 0.36557450733667207
SEED: 3000 - Iter 5
RRMSE: 0.35832982247813483
SEED: 3000 - Iter 6
RRMSE: 0.36509922220992264
SEED: 3000 - Iter 7
RRMSE: 0.36541109442991193
SEED: 3000 - Iter 8
RRMSE: 0.36176884489075617
SEED: 3000 - Iter 9
RRMSE: 0.370168411941004
SEED: 3000 - Iter 10
RRMSE: 0.35875071247241325
SEED: 3000 - Iter 11
RRMSE: 0.36392580229074634
SEED: 3000 - Iter 12
RRMSE: 0.3574373291727201
SEED: 3000 - Iter 13
RRMSE: 0.366052895297371
SEED: 3000 - Iter 14
RRMSE: 0.369405467353018
SEED: 3000 - Iter 15
RRMSE: 0.35870138587704326
SEED: 3000 - Iter 16
RRMSE: 0.3626838682443169
SEED: 3000 - Iter 17
RRMSE: 0.3597755822739579
SEED: 3000 - Iter 18
RRMSE: 0.36305008538854366
SEED: 3000 - Iter 19
RRMSE: 0.36038106776780016
SEED: 3000 - Iter 20
RRMSE: 0.3616816897682529
SEED: 3000 - Iter 21
RRMSE: 0.3576734556021598
SEED: 3000 - Iter 22
RRMSE: 0.360510028105936
SEED: 3000 - Iter 23
RRMSE: 0.3708193991824318
SEED: 3000 - Iter 24
RRMSE: 0.36093946834810364
SEED: 3000 - Iter 25
RRMSE: 0.36281301311882086
SEED: 3000 - Iter 26
RRMSE: 0.3663544124737842
SEED: 3000 - Iter 27
RRMSE: 0.36562047781081497
SEED: 3000 - Iter 28
RRMSE: 0.3528757117293468
SEED: 3000 - Iter 29
RRMSE: 0.3575546185201065
SEED: 3000 - Iter 30
RRMSE: 0.3634350245211145
SEED: 3000 - Iter 31
RRMSE: 0.3631776493988039
SEED: 3000 - Iter 32
RRMSE: 0.35891679773205454
SEED: 3000 - Iter 33
RRMSE: 0.3591686026998814
SEED: 3000 - Iter 34
RRMSE: 0.363865928667365
SEED: 3000 - Iter 35
RRMSE: 0.371145526121837
SEED: 3000 - Iter 36
RRMSE: 0.3526603676640667
SEED: 3000 - Iter 37
RRMSE: 0.3647903006276709
SEED: 3000 - Iter 38
RRMSE: 0.35870138587704326
SEED: 3000 - Iter 39
RRMSE: 0.36496489001198473
SEED: 3000 - Iter 40
RRMSE: 0.3581657669860015
SEED: 3000 - Iter 41
RRMSE: 0.3619797095783227
SEED: 3000 - Iter 42
RRMSE: 0.3683196591856944
SEED: 3000 - Iter 43
RRMSE: 0.36511129309414575
SEED: 3000 - Iter 44
RRMSE: 0.3609877889642208
SEED: 3000 - Iter 45
RRMSE: 0.3689374573788594
SEED: 3000 - Iter 46
RRMSE: 0.3594616879082273
SEED: 3000 - Iter 47
RRMSE: 0.3661940995743064
SEED: 3000 - Iter 48
RRMSE: 0.3606104895581468
SEED: 3000 - Iter 49
RRMSE: 0.36446019261192764
SEED: 3000 - Iter 50
RRMSE: 0.3657733276938532
SEED: 3000 - Iter 51
RRMSE: 0.3625441097595068
SEED: 3000 - Iter 52
RRMSE: 0.36724140208689493
SEED: 3000 - Iter 53
RRMSE: 0.3574105140242374
SEED: 3000 - Iter 54
RRMSE: 0.36989382465936205
SEED: 3000 - Iter 55
RRMSE: 0.3724277916848194
SEED: 3000 - Iter 56
RRMSE: 0.3656484884839952
SEED: 3000 - Iter 57
RRMSE: 0.36314330372474213
SEED: 3000 - Iter 58
RRMSE: 0.3655464574524279
SEED: 3000 - Iter 59
RRMSE: 0.3608618454117284
SEED: 3000 - Iter 60
RRMSE: 0.36021415407033497
SEED: 3000 - Iter 61
RRMSE: 0.36805098091884714
SEED: 3000 - Iter 62
RRMSE: 0.36341514797929564
SEED: 3000 - Iter 63
RRMSE: 0.3588338849195206
SEED: 3000 - Iter 64
RRMSE: 0.35557488110692265
SEED: 3000 - Iter 65
RRMSE: 0.3619167698164271
SEED: 3000 - Iter 66
RRMSE: 0.36977321625919324
SEED: 3000 - Iter 67
RRMSE: 0.3612375079311461
SEED: 3000 - Iter 68
RRMSE: 0.3602948616575137
SEED: 3000 - Iter 69
RRMSE: 0.3646729157490893
SEED: 3000 - Iter 70
RRMSE: 0.3661510383176195
SEED: 3000 - Iter 71
RRMSE: 0.36219566086619126
SEED: 3000 - Iter 72
RRMSE: 0.35955803383186447
SEED: 3000 - Iter 73
RRMSE: 0.35976683420796396
SEED: 3000 - Iter 74
RRMSE: 0.3623076576319035
SEED: 3000 - Iter 75
RRMSE: 0.3569553577585174
SEED: 3000 - Iter 76
RRMSE: 0.3695038892090055
SEED: 3000 - Iter 77
RRMSE: 0.35925290011921585
SEED: 3000 - Iter 78
RRMSE: 0.3664770963867912
SEED: 3000 - Iter 79
RRMSE: 0.3677145414400821
SEED: 3000 - Iter 80
RRMSE: 0.36178225629269145
SEED: 3000 - Iter 81
RRMSE: 0.3598544309513224
SEED: 3000 - Iter 82
RRMSE: 0.3570841002111317
SEED: 3000 - Iter 83
RRMSE: 0.3676495572876543
SEED: 3000 - Iter 84
RRMSE: 0.36055539455006264
SEED: 3000 - Iter 85
RRMSE: 0.3605022113830888
SEED: 3000 - Iter 86
RRMSE: 0.35968883972691645
SEED: 3000 - Iter 87
RRMSE: 0.36205284158416545
SEED: 3000 - Iter 88
RRMSE: 0.3667742051665821
SEED: 3000 - Iter 89
RRMSE: 0.3633971478113602
SEED: 3000 - Iter 90
RRMSE: 0.36238456878378494
SEED: 3000 - Iter 91
RRMSE: 0.3539023523647183
SEED: 3000 - Iter 92
RRMSE: 0.368163390409702
SEED: 3000 - Iter 93
RRMSE: 0.36291558561114623
SEED: 3000 - Iter 94
RRMSE: 0.3668738396452848
SEED: 3000 - Iter 95
RRMSE: 0.3559855250917541
SEED: 3000 - Iter 96
RRMSE: 0.3590714440217325
SEED: 3000 - Iter 97
RRMSE: 0.3650056957652039
SEED: 3000 - Iter 98
RRMSE: 0.36704922980001775
SEED: 3000 - Iter 99
RRMSE: 0.3605997047755357
SEED: 4000 - Iter 0
RRMSE: 0.365452301344123
SEED: 4000 - Iter 1
RRMSE: 0.36853968319082464
SEED: 4000 - Iter 2
RRMSE: 0.3625123779352432
SEED: 4000 - Iter 3
RRMSE: 0.3636233434308122
SEED: 4000 - Iter 4
RRMSE: 0.36245038109764044
SEED: 4000 - Iter 5
RRMSE: 0.3673712728244428
SEED: 4000 - Iter 6
RRMSE: 0.3633387867658987
SEED: 4000 - Iter 7
RRMSE: 0.36673612458138644
SEED: 4000 - Iter 8
RRMSE: 0.3632426394053008
SEED: 4000 - Iter 9
RRMSE: 0.36588447350252273
SEED: 4000 - Iter 10
RRMSE: 0.3696380934483383
SEED: 4000 - Iter 11
RRMSE: 0.36452978568434047
SEED: 4000 - Iter 12
RRMSE: 0.3631674069075418
SEED: 4000 - Iter 13
RRMSE: 0.36969306718718586
SEED: 4000 - Iter 14
RRMSE: 0.3626502476739002
SEED: 4000 - Iter 15
RRMSE: 0.3680110498751134
SEED: 4000 - Iter 16
RRMSE: 0.36248535262938997
SEED: 4000 - Iter 17
RRMSE: 0.3634903378419972
SEED: 4000 - Iter 18
RRMSE: 0.3617892871472201
SEED: 4000 - Iter 19
RRMSE: 0.3697976372932991
SEED: 4000 - Iter 20
RRMSE: 0.36012903240317473
SEED: 4000 - Iter 21
RRMSE: 0.3579836080644523
SEED: 4000 - Iter 22
RRMSE: 0.3576909212168116
SEED: 4000 - Iter 23
RRMSE: 0.3601472362731362
SEED: 4000 - Iter 24
RRMSE: 0.3671536104151955
SEED: 4000 - Iter 25
RRMSE: 0.3646856593641886
SEED: 4000 - Iter 26
RRMSE: 0.35921451907622826
SEED: 4000 - Iter 27
RRMSE: 0.3641262878175292
SEED: 4000 - Iter 28
RRMSE: 0.3637339606521416
SEED: 4000 - Iter 29
RRMSE: 0.3654954521673633
SEED: 4000 - Iter 30
RRMSE: 0.3582137759305732
SEED: 4000 - Iter 31
RRMSE: 0.3667244951530081
SEED: 4000 - Iter 32
RRMSE: 0.3695479744967743
SEED: 4000 - Iter 33
RRMSE: 0.3603740845621444
SEED: 4000 - Iter 34
RRMSE: 0.361890267264165
SEED: 4000 - Iter 35
RRMSE: 0.3591306968616571
SEED: 4000 - Iter 36
RRMSE: 0.36508613172005877
SEED: 4000 - Iter 37
RRMSE: 0.3657814613008993
SEED: 4000 - Iter 38
RRMSE: 0.36814464698010074
SEED: 4000 - Iter 39
RRMSE: 0.3543685210941049
SEED: 4000 - Iter 40
RRMSE: 0.3594667861627272
SEED: 4000 - Iter 41
RRMSE: 0.36492100207596656
SEED: 4000 - Iter 42
RRMSE: 0.36512169333386807
SEED: 4000 - Iter 43
RRMSE: 0.36019210659712064
SEED: 4000 - Iter 44
RRMSE: 0.35732474800035197
SEED: 4000 - Iter 45
RRMSE: 0.3616282085301423
SEED: 4000 - Iter 46
RRMSE: 0.3659955930420208
SEED: 4000 - Iter 47
RRMSE: 0.3598751358139336
SEED: 4000 - Iter 48
RRMSE: 0.36303290942752714
SEED: 4000 - Iter 49
RRMSE: 0.36821326998287823
SEED: 4000 - Iter 50
RRMSE: 0.36570703888979617
SEED: 4000 - Iter 51
RRMSE: 0.3711178167448758
SEED: 4000 - Iter 52
RRMSE: 0.3643361512084754
SEED: 4000 - Iter 53
RRMSE: 0.36304777517998
SEED: 4000 - Iter 54
RRMSE: 0.3642571781968354
SEED: 4000 - Iter 55
RRMSE: 0.36356783063970044
SEED: 4000 - Iter 56
RRMSE: 0.36287327741478326
SEED: 4000 - Iter 57
RRMSE: 0.3621079134029438
SEED: 4000 - Iter 58
RRMSE: 0.36359395230395875
SEED: 4000 - Iter 59
RRMSE: 0.361920452743768
SEED: 4000 - Iter 60
RRMSE: 0.3623064363926328
SEED: 4000 - Iter 61
RRMSE: 0.36257067586670855
SEED: 4000 - Iter 62
RRMSE: 0.3703018894112817
SEED: 4000 - Iter 63
RRMSE: 0.3709366680864799
SEED: 4000 - Iter 64
RRMSE: 0.36218312045905643
SEED: 4000 - Iter 65
RRMSE: 0.3646768023407384
SEED: 4000 - Iter 66
RRMSE: 0.3686966315284493
SEED: 4000 - Iter 67
RRMSE: 0.3665983559367523
SEED: 4000 - Iter 68
RRMSE: 0.3670885571720673
SEED: 4000 - Iter 69
RRMSE: 0.35870138587704326
SEED: 4000 - Iter 70
RRMSE: 0.3617867201976462
SEED: 4000 - Iter 71
RRMSE: 0.35670159782531885
SEED: 4000 - Iter 72
RRMSE: 0.3660811378912073
SEED: 4000 - Iter 73
RRMSE: 0.36888110571359733
SEED: 4000 - Iter 74
RRMSE: 0.36487443585416307
SEED: 4000 - Iter 75
RRMSE: 0.36535486918880444
SEED: 4000 - Iter 76
RRMSE: 0.3625167812271009
SEED: 4000 - Iter 77
RRMSE: 0.3586716024848289
SEED: 4000 - Iter 78
RRMSE: 0.35588794216565317
SEED: 4000 - Iter 79
RRMSE: 0.36166793979888745
SEED: 4000 - Iter 80
RRMSE: 0.36252469991570746
SEED: 4000 - Iter 81
RRMSE: 0.3631936090388684
SEED: 4000 - Iter 82
RRMSE: 0.360869087181069
SEED: 4000 - Iter 83
RRMSE: 0.36206877197372356
SEED: 4000 - Iter 84
RRMSE: 0.3641667574674698
SEED: 4000 - Iter 85
RRMSE: 0.36971018787106
SEED: 4000 - Iter 86
RRMSE: 0.3604676224454142
SEED: 4000 - Iter 87
RRMSE: 0.3614153641586536
SEED: 4000 - Iter 88
RRMSE: 0.3633461320423366
SEED: 4000 - Iter 89
RRMSE: 0.37510882855445926
SEED: 4000 - Iter 90
RRMSE: 0.36894562165736083
SEED: 4000 - Iter 91
RRMSE: 0.36595686953347295
SEED: 4000 - Iter 92
RRMSE: 0.36037094334812
SEED: 4000 - Iter 93
RRMSE: 0.3644146975427828
SEED: 4000 - Iter 94
RRMSE: 0.365744023050799
SEED: 4000 - Iter 95
RRMSE: 0.3608544503897255
SEED: 4000 - Iter 96
RRMSE: 0.3687151969025947
SEED: 4000 - Iter 97
RRMSE: 0.36451044394013643
SEED: 4000 - Iter 98
RRMSE: 0.3557350143137289
SEED: 4000 - Iter 99
RRMSE: 0.37541208551950767
SEED: 5000 - Iter 0
RRMSE: 0.36071859693879704
SEED: 5000 - Iter 1
RRMSE: 0.35708377512569967
SEED: 5000 - Iter 2
RRMSE: 0.36038639955905627
SEED: 5000 - Iter 3
RRMSE: 0.35671114491936834
SEED: 5000 - Iter 4
RRMSE: 0.3650401889638313
SEED: 5000 - Iter 5
RRMSE: 0.3522617948740727
SEED: 5000 - Iter 6
RRMSE: 0.36648375727491755
SEED: 5000 - Iter 7
RRMSE: 0.36757472308159683
SEED: 5000 - Iter 8
RRMSE: 0.3567108349089865
SEED: 5000 - Iter 9
RRMSE: 0.3606417372175982
SEED: 5000 - Iter 10
RRMSE: 0.36285825899449015
SEED: 5000 - Iter 11
RRMSE: 0.36688724702911796
SEED: 5000 - Iter 12
RRMSE: 0.3621281925072236
SEED: 5000 - Iter 13
RRMSE: 0.36380157270698144
SEED: 5000 - Iter 14
RRMSE: 0.3637462671867786
SEED: 5000 - Iter 15
RRMSE: 0.36829629426144983
SEED: 5000 - Iter 16
RRMSE: 0.36230921917060965
SEED: 5000 - Iter 17
RRMSE: 0.3636771890219605
SEED: 5000 - Iter 18
RRMSE: 0.36408180686318303
SEED: 5000 - Iter 19
RRMSE: 0.36471796656862254
SEED: 5000 - Iter 20
RRMSE: 0.36483328634353923
SEED: 5000 - Iter 21
RRMSE: 0.3575030542492464
SEED: 5000 - Iter 22
RRMSE: 0.3597352723703196

                                              FEATURES    RRMSE
0    (TEMP_MÉD_ACC_MENS, TEMP_MIN_MAX_MENS, TEMP_MI...  0.35921
1    (TEMP_MÉD_ACC_MENS, PRECIPITAÇÃO_MÉD_MENS, TEM...  0.36290
2    (TEMP_MIN_MÉD_MENS, TEMP_MÉD_MIN_MENS, TEMP_MÉ...  0.36678
3    (TEMP_MIN_MÉD_MENS, TEMP_MÉD_MIN_MENS, TEMP_MÉ...  0.36511
4    (TEMP_MIN_MÉD_MENS, TEMP_MÉD_MAX_MENS, TEMP_MÉ...  0.35892
..                                                 ...      ...
986  (TEMP_MÉD_MÉD_MENS, TEMP_MÉD_ACC_MENS, TEMP_MI...  0.36763
987  (TEMP_MÉD_MÉD_MENS, TEMP_MÉD_ACC_MENS, TEMP_MI...  0.37153
988  (TEMP_MÉD_MAX_MENS, TEMP_MÉD_ACC_MENS, PRECIPI...  0.35888
989  (TEMP_MÉD_ACC_MENS, PRECIPITAÇÃO_MÉD_MENS, TEM...  0.36603
990  (TEMP_MIN_MÉD_MENS, TEMP_MÉD_ACC_MENS, TEMP_MI...  0.36571

[991 rows x 2 columns]

In [11]:
fitness_regressao = pd.read_csv("./resultados/features/fitness_features_regressao.csv", sep=";", decimal=".")
fitness_regressao["RRMSE"] = fitness_regressao["RRMSE"].round(5)
fitness_regressao = fitness_regressao.sort_values("RRMSE")
fitness_regressao

                                              FEATURES    RRMSE
752  ('TEMP_MÉD_ACC_MENS', 'TEMP_MIN_MAX_MENS', 'TE...  0.35194
405  ('TEMP_MÉD_MAX_MENS', 'TEMP_MÉD_ACC_MENS', 'PR...  0.35226
236  ('TEMP_MÉD_ACC_MENS', 'TEMP_MIN_ACC_MENS', 'TE...  0.35266
824  ('TEMP_MÉD_ACC_MENS', 'TEMP_MIN_ACC_MENS', 'TE...  0.35286
228  ('TEMP_MÉD_MAX_MENS', 'TEMP_MÉD_ACC_MENS', 'TE...  0.35288
..                                                 ...      ...
726  ('TEMP_MÉD_ACC_MENS', 'TEMP_MIN_ACC_MENS', 'TE...  0.37573
816  ('TEMP_MÉD_MIN_MENS', 'TEMP_MÉD_MAX_MENS', 'TE...  0.37592
911  ('TEMP_MIN_MÉD_MENS', 'TEMP_MÉD_MIN_MENS', 'TE...  0.37688
114  ('TEMP_MÉD_MÉD_MENS', 'TEMP_MÉD_ACC_MENS', 'TE...  0.37718
952  ('TEMP_MIN_MÉD_MENS', 'TEMP_MÉD_ACC_MENS', 'TE...  0.37961

[991 rows x 2 columns]

In [12]:
fitness_regressao = fitness_regressao.sort_values("RRMSE").head(1).reset_index(drop=True)
fitness_regressao = pd.DataFrame(
    str(fitness_regressao.iloc[0]["FEATURES"]).replace("(", '').replace(")", '').replace("'", "").split(", "),
    columns=["FEATURES"])

fitness_regressao

                    FEATURES
0          TEMP_MÉD_ACC_MENS
1          TEMP_MIN_MAX_MENS
2          TEMP_MIN_ACC_MENS
3      PRECIPITAÇÃO_MIN_MENS
4          TEMP_MAX_ACC_MENS
5      PRECIPITAÇÃO_MAX_MENS
6          DIA_DA_SEMANA_sex
7                    MÊS_abr
8                    MÊS_jul
9                    MÊS_mai
10                   MÊS_mar
11                  ANO_2024
12                  ANO_2015
13                  ANO_2017
14                  ANO_2020
15                  ANO_2014
16          CAMPUS_ARAPONGAS
17        CAMPUS_CAMPO LARGO
18            CAMPUS_COLOMBO
19  CAMPUS_LONDRINA - CENTRO
20   CAMPUS_LONDRINA - NORTE
21          CAMPUS_PARANAVAÍ
22   CAMPUS_QUEDAS DO IGUAÇU
23      CURSOS_GRAD_MATUTINO
24    CURSOS_GRAD_VESPERTINO
25                    FÉRIAS
26                     COVID
27                     ORDEM
28                    LAG_01
29                    LAG_02
30                    LAG_03
31                    LAG_04
32                    LAG_05
33                    LAG_06
34                    LAG_08
35                    LAG_11
36                    LAG_12