
# Importações

In [12]:
import os
import random
import warnings

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_percentage_error as mape, root_mean_squared_error
from sklearn.neural_network import MLPRegressor
from sklearn.preprocessing import MinMaxScaler

from pyESN import ESN
from shap.plots import colors
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor
from wsb import WSB

MODELOS = ["ESN", "MLP", "RF", "XGBoost", "WSB"]
SEED = 100
SEEDS = [1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000, 10000]
HORIZONTES = [3, 6, 12]


def reset_seed(rnd_seed=SEED):
    os.environ['PYTHONHASHSEED'] = '0'
    random.seed(rnd_seed)
    np.random.seed(rnd_seed)


def calcular_rrmse(y_true, y_pred):
    y_true = np.array(y_true)
    y_pred = np.array(y_pred)

    rmse = root_mean_squared_error(y_true, y_pred)

    mean_y_true = np.mean(y_true)

    rrmse = rmse / mean_y_true
    return rrmse


warnings.filterwarnings("ignore")
reset_seed()

# Carregar Datasets

In [13]:
df = pd.read_csv("./dados/dados_tratados.csv", sep=';', decimal='.')

## Normalização

In [14]:
# Repete a normalização para obtermos so scalers correspondentes
scalers = {}
dataframes = []

for campus, dados in df.groupby("CAMPUS"):
    scaler = MinMaxScaler()
    dados[["CONSUMO"]] = scaler.fit_transform(dados[["CONSUMO"]])

    scalers[campus] = scaler
    dataframes.append(dados)

df = pd.concat(dataframes, ignore_index=True)

## Criação dos Lags

In [15]:
dataframes = []

for campus, dados in df.sort_values("DATA").groupby("CAMPUS"):
    lags = {f'LAG_{i:02d}': dados['CONSUMO'].shift(i) for i in range(1, 12 + 1)}
    dados = pd.concat([dados, pd.DataFrame(lags)], axis=1)
    dados.dropna(inplace=True)
    dados["ORDEM"] = range(1, len(dados) + 1)
    dataframes.append(dados)

df = pd.concat(dataframes, ignore_index=True)
df

,CONSUMO,DATA,TEMP_MIN_MÉD_MENS,TEMP_MÉD_MIN_MENS,TEMP_MÉD_MÉD_MENS,TEMP_MÉD_MAX_MENS,TEMP_MÉD_ACC_MENS,TEMP_MAX_MÉD_MENS,PRECIPITAÇÃO_MÉD_MENS,TEMP_MIN_MIN_MENS,...,LAG_03,LAG_04,LAG_05,LAG_06,LAG_07,LAG_08,LAG_09,LAG_10,LAG_11,LAG_12
0,0.615105,2016-02-29,19,22,25,28,734,33,4,19,...,0.570938,0.553762,0.386907,0.331354,0.302547,0.384551,0.530844,0.643078,0.846886,0.502037
1,0.711047,2016-03-31,12,17,22,28,685,32,3,12,...,0.580507,0.570938,0.553762,0.386907,0.331354,0.302547,0.384551,0.530844,0.643078,0.846886
2,0.633361,2016-04-30,4,9,23,28,702,33,2,4,...,0.424204,0.580507,0.570938,0.553762,0.386907,0.331354,0.302547,0.384551,0.530844,0.643078
3,0.406291,2016-05-31,4,11,16,22,490,27,9,4,...,0.615105,0.424204,0.580507,0.570938,0.553762,0.386907,0.331354,0.302547,0.384551,0.530844
4,0.362467,2016-06-30,-1,7,14,20,408,27,3,-1,...,0.711047,0.615105,0.424204,0.580507,0.570938,0.553762,0.386907,0.331354,0.302547,0.384551
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2090,0.359224,2024-06-30,0,8,17,20,499,26,1,0,...,0.990145,0.803327,0.457985,0.822613,0.794744,0.559818,0.747059,0.839038,0.553248,0.743880
2091,1.000000,2024-07-31,1,9,13,18,413,25,6,1,...,0.680301,0.990145,0.803327,0.457985,0.822613,0.794744,0.559818,0.747059,0.839038,0.553248
2092,0.940871,2024-08-31,-3,7,15,21,468,31,1,-3,...,0.352866,0.680301,0.990145,0.803327,0.457985,0.822613,0.794744,0.559818,0.747059,0.839038
2093,0.788386,2024-09-30,10,13,20,24,591,34,3,10,...,0.359224,0.352866,0.680301,0.990145,0.803327,0.457985,0.822613,0.794744,0.559818,0.747059
2094,0.865317,2024-10-31,10,14,20,25,610,33,3,10,...,1.000000,0.359224,0.352866,0.680301,0.990145,0.803327,0.457985,0.822613,0.794744,0.559818

## Melhores Features

In [16]:
df_features = pd.read_csv("./resultados/features/fitness_features_regressao.csv", sep=";", decimal=".")

df_features = df_features.sort_values("RRMSE").head(1).reset_index(drop=True)
df_features = pd.DataFrame(
    columns=str(df_features.iloc[0]["FEATURES"]).replace("(", '').replace(")", '').replace("'", "").split(", "))

df_features = df_features.columns

df_features

Index(['TEMP_MÉD_MIN_MENS', 'TEMP_MÉD_MÉD_MENS', 'PRECIPITAÇÃO_MÉD_MENS',
       'TEMP_MIN_MAX_MENS', 'TEMP_MAX_MIN_MENS', 'PRECIPITAÇÃO_MIN_MENS',
       'TEMP_MAX_MAX_MENS', 'DIA_DA_SEMANA_dom', 'DIA_DA_SEMANA_seg',
       'DIA_DA_SEMANA_sáb', 'DIA_DA_SEMANA_ter', 'MÊS_abr', 'MÊS_ago',
       'MÊS_fev', 'MÊS_jun', 'MÊS_mai', 'MÊS_nov', 'ANO_2021', 'ANO_2022',
       'ANO_2023', 'ANO_2015', 'ANO_2016', 'ANO_2017', 'ANO_2018', 'ANO_2019',
       'CAMPUS_ASTORGA', 'CAMPUS_CAMPO LARGO', 'CAMPUS_CAPANEMA',
       'CAMPUS_CASCAVEL', 'CAMPUS_CORONEL VIVIDA', 'CAMPUS_CURITIBA',
       'CAMPUS_GOIOERÊ', 'CAMPUS_IVAIPORÃ', 'CAMPUS_JAGUARIAÍVA',
       'CAMPUS_LONDRINA - CENTRO', 'CAMPUS_PALMAS', 'CAMPUS_PARANAGUÁ',
       'CAMPUS_PINHAIS', 'CAMPUS_TELÊMACO BORBA', 'CAMPUS_UMUARAMA',
       'CURSOS_TEC_SUBSEQUENTE', 'CURSOS_GRAD_MATUTINO',
       'CURSOS_GRAD_VESPERTINO', 'CURSOS_GRAD_NOTURNO', 'CURSOS_POS', 'FÉRIAS',
       'COVID', 'LAG_01', 'LAG_02', 'LAG_03', 'LAG_05', 'LAG_07', 'LAG_09'],
      dtype='object')

## Melhores Parâmetros

In [17]:
def get_modelo(nome, tipo_treino=None, campus=None):
    if nome == "ESN":
        return ESN(n_inputs=df_features.shape[0],
                   n_outputs=1,
                   n_reservoir=int(best["ESN"]["Reservoirs"]),
                   sparsity=best["ESN"]["Sparsity"],
                   spectral_radius=best["ESN"]["Spectral Radius"],
                   random_state=int(best["ESN"]["SEED"]))

    if nome == "MLP":
        mlp = MLPRegressor(hidden_layer_sizes=(int(best["MLP"]["Hidden Layers"]),),
                           activation=best["MLP"]["Activation"],
                           alpha=best["MLP"]["Alpha"],
                           random_state=int(best["MLP"]["SEED"]))
        return mlp

    if nome == "RF":
        return RandomForestRegressor(random_state=int(best["RF"]["SEED"]),
                                     n_estimators=int(best["RF"]["N_estimators"]),
                                     max_depth=int(best["RF"]["Max_depth"]),
                                     min_samples_split=int(best["RF"]["Min_samples_split"]),
                                     min_samples_leaf=int(best["RF"]["Min_samples_leaf"]))

    if nome == "XGBoost":
        return XGBRegressor(random_state=int(best["XGBoost"]["SEED"]),
                            n_estimators=int(best["XGBoost"]["N_estimators"]),
                            max_depth=int(best["XGBoost"]["Max_depth"]),
                            booster=best["XGBoost"]["Booster"],
                            reg_lambda=best["XGBoost"]["Lambda"],
                            reg_alpha=best["XGBoost"]["Alpha"],
                            updater="coord_descent" if best["XGBoost"]["Booster"] == "gblinear" else None)

    if nome == "WSB":
        return WSB(strong_predictor=get_modelo(wsb_prev_forte[tipo_treino]),
                   weak_predictors=[get_modelo(m) for m in MODELOS if m != "WSB" and m != strong_pred],
                   weight_g=wsb_pesos[(campus, tipo_treino)])


wsb_prev_forte = {"local": "XGBoost", "global": "ESN"}
wsb_pesos = {}
best = {}
for modelo in MODELOS:
    if modelo == "WSB":
        continue
    df_aux = pd.read_csv(
        f"./resultados/otimização - regressão/BEST {modelo}.csv", sep=';',
        decimal='.', header=0)

    best[modelo] = df_aux.iloc[0]

for key, val in best.items():
    display(val)

OTIMIZADOR           PSO
MODELO               ESN
SEED                9000
Reservoirs          11.0
Sparsity            0.23
Spectral Radius    0.639
Fitness            0.289
Name: 0, dtype: object

OTIMIZADOR         PSO
MODELO             MLP
SEED             10000
Hidden Layers      220
Alpha            0.979
Activation        relu
Fitness          0.227
Name: 0, dtype: object

OTIMIZADOR             PSO
MODELO                  RF
SEED                  7000
N_estimators          15.0
Max_depth            232.0
Min_samples_split     11.0
Min_samples_leaf       4.0
Fitness              0.247
Name: 0, dtype: object

OTIMIZADOR          PSO
MODELO          XGBoost
SEED               5000
N_estimators        242
Max_depth           119
Booster          gbtree
Lambda            0.898
Alpha             0.041
Fitness           0.243
Name: 0, dtype: object

# Divisão dos Dados

In [18]:
dfs_treino = {}
dfs_teste = {}
for horizonte in HORIZONTES:
    treino = []
    teste = []

    for campus, dados in df.sort_values('DATA').groupby("CAMPUS"):
        dados["CAMPUS"] = campus

        dados_treino, dados_teste = train_test_split(dados, test_size=horizonte, shuffle=False)

        treino.append(dados_treino)
        teste.append(dados_teste)

    treino = pd.DataFrame(pd.concat(treino, ignore_index=True))
    teste = pd.DataFrame(pd.concat(teste, ignore_index=True))

    dfs_treino[horizonte] = treino
    dfs_teste[horizonte] = teste

# Execução dos Experimentos

In [19]:
def treino(previsor, dados_treino, features):
    x_treino = dados_treino[features].to_numpy()
    y_treino = dados_treino["CONSUMO"].to_numpy()

    previsor.fit(x_treino, y_treino)
    return previsor


def teste(previsor, historico_campus, x_teste, features, horizonte):
    historico = historico_campus[["CONSUMO"]].copy()
    x_teste = x_teste[features].copy()

    previsoes = []

    for i_test in range(horizonte):
        row = x_teste.iloc[[i_test]].copy()
        historico = pd.concat([historico, pd.DataFrame([0], columns=["CONSUMO"], index=[i_test])], axis=0)

        # Recalcula os lags conforme os valores previstos pelo modelo
        lags = pd.DataFrame({f'LAG_{i:02d}': historico["CONSUMO"].shift(i) for i in range(1, 12 + 1) if
                             f'LAG_{i:02d}' in features}).tail(1)
        row.update(lags)

        if isinstance(previsor, WSB) and horizonte >= 6:
            peso_t = i_test / horizonte
            prev = previsor.predict(row.to_numpy(), peso_t)[0]
        elif isinstance(previsor, ESN):
            prev = previsor.predict(row.to_numpy())[0][0]
        else:
            prev = previsor.predict(row.to_numpy())[0]

        row["CONSUMO"] = prev
        previsoes.append(prev)
        historico.update(row)

    return pd.DataFrame({"CONSUMO PREVISTO": previsoes}, index=x_teste.index)

## Definição dos Previsores Fortes - Local

In [20]:
# Treinamento local
for horizonte in HORIZONTES:
    for campus, dados in dfs_treino[horizonte].sort_values("DATA").groupby("CAMPUS"):
        dados = dados.set_index('DATA')
        dados_treino, dados_teste = train_test_split(dados, test_size=horizonte, shuffle=False)

        erros = []
        # Treina o modelo com os dados do campus atual
        strong_pred = get_modelo(wsb_prev_forte["local"])
        weak_preds = [get_modelo(m) for m in MODELOS if m != "WSB" and m != strong_pred]
        modelo = WSB(strong_predictor=strong_pred, weak_predictors=weak_preds, weight_g=-1)
        modelo = treino(modelo, dados, df_features)

        # Testa o modelo com os dados do campus atual
        previsoes = teste(modelo, dados, dados_teste, df_features, horizonte)
        erro = (dados_teste["CONSUMO"].mean() - previsoes["CONSUMO PREVISTO"].mean()) / dados_teste["CONSUMO"].mean()

        # Atualiza o peso individual do campus
        wsb_pesos[(campus, "local")] = -1 + erro

    # Converte o dicionário wsb_prev_forte em um DataFrame
    df_wsb_pesos = pd.DataFrame.from_dict(wsb_pesos, orient="index", columns=["WEIGHT_G"])
    df_wsb_pesos.index = pd.MultiIndex.from_tuples(df_wsb_pesos.index, names=["CAMPUS", "TIPO_TREINAMENTO"])

    # Salva o DataFrame em um arquivo CSV
    df_wsb_pesos.to_csv(f"./resultados/WSB - Previsores Fortes {horizonte}M.csv", sep=';', decimal='.')
    display(df_wsb_pesos)

                                      WEIGHT_G
CAMPUS              TIPO_TREINAMENTO
ASSIS CHATEAUBRIAND local            -1.191047
ASTORGA             local            -0.987997
BARRACÃO            local            -1.016882
CAMPO LARGO         local            -1.531455
CAPANEMA            local            -1.201758
CASCAVEL            local            -1.559937
CORONEL VIVIDA      local            -0.945570
CURITIBA            local            -1.735160
FOZ DO IGUAÇU       local            -1.222505
GOIOERÊ             local            -1.765745
IRATI               local            -1.143471
IVAIPORÃ            local            -1.237020
JACAREZINHO         local            -1.209345
JAGUARIAÍVA         local            -1.059670
LONDRINA - CENTRO   local            -1.314812
PALMAS              local            -0.951329
PARANAGUÁ           local            -1.120749
PARANAVAÍ           local            -1.009165
PINHAIS             local            -1.235082
PITANGA             local            -1.174246
QUEDAS DO IGUAÇU    local            -0.987256
TELÊMACO BORBA      local            -1.179669
UMUARAMA            local            -2.455017
UNIÃO DA VITÓRIA    local            -1.141597

                                      WEIGHT_G
CAMPUS              TIPO_TREINAMENTO
ASSIS CHATEAUBRIAND local            -0.980699
ASTORGA             local            -0.980289
BARRACÃO            local            -0.962277
CAMPO LARGO         local            -1.009235
CAPANEMA            local            -0.995431
CASCAVEL            local            -0.980343
CORONEL VIVIDA      local            -1.042649
CURITIBA            local            -0.894920
FOZ DO IGUAÇU       local            -1.048677
GOIOERÊ             local            -0.958549
IRATI               local            -0.928368
IVAIPORÃ            local            -0.932414
JACAREZINHO         local            -0.970674
JAGUARIAÍVA         local            -0.967545
LONDRINA - CENTRO   local            -0.986534
PALMAS              local            -0.998678
PARANAGUÁ           local            -0.997597
PARANAVAÍ           local            -1.034945
PINHAIS             local            -1.022616
PITANGA             local            -0.940541
QUEDAS DO IGUAÇU    local            -0.982088
TELÊMACO BORBA      local            -0.976820
UMUARAMA            local            -0.957078
UNIÃO DA VITÓRIA    local            -0.960618

                                      WEIGHT_G
CAMPUS              TIPO_TREINAMENTO
ASSIS CHATEAUBRIAND local            -0.997149
ASTORGA             local            -0.993090
BARRACÃO            local            -0.974075
CAMPO LARGO         local            -1.007456
CAPANEMA            local            -1.009112
CASCAVEL            local            -0.985850
CORONEL VIVIDA      local            -0.991439
CURITIBA            local            -1.012236
FOZ DO IGUAÇU       local            -1.013342
GOIOERÊ             local            -0.970021
IRATI               local            -0.982273
IVAIPORÃ            local            -0.987414
JACAREZINHO         local            -0.968605
JAGUARIAÍVA         local            -0.988635
LONDRINA - CENTRO   local            -0.991545
PALMAS              local            -1.005416
PARANAGUÁ           local            -0.982102
PARANAVAÍ           local            -0.959757
PINHAIS             local            -1.010320
PITANGA             local            -0.996501
QUEDAS DO IGUAÇU    local            -0.988104
TELÊMACO BORBA      local            -0.986452
UMUARAMA            local            -0.972794
UNIÃO DA VITÓRIA    local            -0.991076

## Definição dos Previsores Fortes - Global

In [21]:
# Treinamento global
for horizonte in HORIZONTES:
    df_aux_treino = []
    df_aux_test = []

    for campus, dados in dfs_treino[horizonte].sort_values("DATA").groupby("CAMPUS"):
        dados_treino, dados_teste = train_test_split(dados, test_size=horizonte, shuffle=False)
        df_aux_treino.append(dados_treino)
        df_aux_test.append(dados_teste)

    df_aux_treino = pd.DataFrame(pd.concat(df_aux_treino, ignore_index=True))
    df_aux_test = pd.DataFrame(pd.concat(df_aux_test, ignore_index=True))

    for campus, dados in df_aux_test.sort_values("DATA").groupby("CAMPUS"):
        dados = dados.set_index('DATA')

        # Treina o modelo com os dados de todos os campi
        strong_pred = get_modelo(wsb_prev_forte["global"])
        weak_preds = [get_modelo(m) for m in MODELOS if m != "WSB" and m != strong_pred]
        modelo = WSB(strong_predictor=strong_pred, weak_predictors=weak_preds, weight_g=-1)
        modelo = treino(modelo, df_aux_treino, df_features)

        # Testa o modelo com os dados do campus atual
        previsoes = teste(modelo, df_aux_treino[df_aux_treino["CAMPUS"] == campus], dados, df_features, horizonte)
        erro = (dados["CONSUMO"].mean() - previsoes["CONSUMO PREVISTO"].mean()) / dados["CONSUMO"].mean()

        # Atualiza o peso individual do campus
        wsb_pesos[(campus, "global")] = -1 + erro

    # Converte o dicionário wsb_prev_forte em um DataFrame
    df_wsb_pesos = pd.DataFrame.from_dict(wsb_pesos, orient="index", columns=["WEIGHT_G"])
    df_wsb_pesos.index = pd.MultiIndex.from_tuples(df_wsb_pesos.index, names=["CAMPUS", "TIPO_TREINAMENTO"])

    # Salva o DataFrame em um arquivo CSV
    df_wsb_pesos.to_csv(f"./resultados/WSB - Previsores Fortes {horizonte}M.csv", sep=';', decimal='.')
    display(df_wsb_pesos)

                                      WEIGHT_G
CAMPUS              TIPO_TREINAMENTO
ASSIS CHATEAUBRIAND local            -0.997149
ASTORGA             local            -0.993090
BARRACÃO            local            -0.974075
CAMPO LARGO         local            -1.007456
CAPANEMA            local            -1.009112
CASCAVEL            local            -0.985850
CORONEL VIVIDA      local            -0.991439
CURITIBA            local            -1.012236
FOZ DO IGUAÇU       local            -1.013342
GOIOERÊ             local            -0.970021
IRATI               local            -0.982273
IVAIPORÃ            local            -0.987414
JACAREZINHO         local            -0.968605
JAGUARIAÍVA         local            -0.988635
LONDRINA - CENTRO   local            -0.991545
PALMAS              local            -1.005416
PARANAGUÁ           local            -0.982102
PARANAVAÍ           local            -0.959757
PINHAIS             local            -1.010320
PITANGA             local            -0.996501
QUEDAS DO IGUAÇU    local            -0.988104
TELÊMACO BORBA      local            -0.986452
UMUARAMA            local            -0.972794
UNIÃO DA VITÓRIA    local            -0.991076
ASSIS CHATEAUBRIAND global           -2.047857
ASTORGA             global           -0.978656
BARRACÃO            global           -0.981706
CAMPO LARGO         global           -1.805123
CAPANEMA            global           -1.770574
CASCAVEL            global           -2.033191
CORONEL VIVIDA      global           -0.863728
CURITIBA            global           -2.103587
FOZ DO IGUAÇU       global           -1.554643
GOIOERÊ             global           -2.948706
IRATI               global           -1.216397
IVAIPORÃ            global           -1.267225
JACAREZINHO         global           -2.261416
JAGUARIAÍVA         global           -0.908143
LONDRINA - CENTRO   global           -2.683656
PALMAS              global           -0.837521
PARANAGUÁ           global           -1.523355
PARANAVAÍ           global           -2.451828
PINHAIS             global           -1.581222
PITANGA             global           -1.152358
QUEDAS DO IGUAÇU    global           -1.044496
TELÊMACO BORBA      global           -1.033800
UMUARAMA            global           -4.245109
UNIÃO DA VITÓRIA    global           -0.903628

                                      WEIGHT_G
CAMPUS              TIPO_TREINAMENTO
ASSIS CHATEAUBRIAND local            -0.997149
ASTORGA             local            -0.993090
BARRACÃO            local            -0.974075
CAMPO LARGO         local            -1.007456
CAPANEMA            local            -1.009112
CASCAVEL            local            -0.985850
CORONEL VIVIDA      local            -0.991439
CURITIBA            local            -1.012236
FOZ DO IGUAÇU       local            -1.013342
GOIOERÊ             local            -0.970021
IRATI               local            -0.982273
IVAIPORÃ            local            -0.987414
JACAREZINHO         local            -0.968605
JAGUARIAÍVA         local            -0.988635
LONDRINA - CENTRO   local            -0.991545
PALMAS              local            -1.005416
PARANAGUÁ           local            -0.982102
PARANAVAÍ           local            -0.959757
PINHAIS             local            -1.010320
PITANGA             local            -0.996501
QUEDAS DO IGUAÇU    local            -0.988104
TELÊMACO BORBA      local            -0.986452
UMUARAMA            local            -0.972794
UNIÃO DA VITÓRIA    local            -0.991076
ASSIS CHATEAUBRIAND global           -0.986414
ASTORGA             global           -0.950980
BARRACÃO            global           -0.859166
CAMPO LARGO         global           -1.186952
CAPANEMA            global           -1.016395
CASCAVEL            global           -0.970119
CORONEL VIVIDA      global           -1.024806
CURITIBA            global           -1.122969
FOZ DO IGUAÇU       global           -1.226766
GOIOERÊ             global           -0.902137
IRATI               global           -0.856683
IVAIPORÃ            global           -0.891921
JACAREZINHO         global           -1.007254
JAGUARIAÍVA         global           -0.899920
LONDRINA - CENTRO   global           -1.019317
PALMAS              global           -1.136713
PARANAGUÁ           global           -0.900346
PARANAVAÍ           global           -1.184324
PINHAIS             global           -1.067174
PITANGA             global           -0.882800
QUEDAS DO IGUAÇU    global           -1.168249
TELÊMACO BORBA      global           -0.993004
UMUARAMA            global           -0.898606
UNIÃO DA VITÓRIA    global           -0.890453

                                      WEIGHT_G
CAMPUS              TIPO_TREINAMENTO
ASSIS CHATEAUBRIAND local            -0.997149
ASTORGA             local            -0.993090
BARRACÃO            local            -0.974075
CAMPO LARGO         local            -1.007456
CAPANEMA            local            -1.009112
CASCAVEL            local            -0.985850
CORONEL VIVIDA      local            -0.991439
CURITIBA            local            -1.012236
FOZ DO IGUAÇU       local            -1.013342
GOIOERÊ             local            -0.970021
IRATI               local            -0.982273
IVAIPORÃ            local            -0.987414
JACAREZINHO         local            -0.968605
JAGUARIAÍVA         local            -0.988635
LONDRINA - CENTRO   local            -0.991545
PALMAS              local            -1.005416
PARANAGUÁ           local            -0.982102
PARANAVAÍ           local            -0.959757
PINHAIS             local            -1.010320
PITANGA             local            -0.996501
QUEDAS DO IGUAÇU    local            -0.988104
TELÊMACO BORBA      local            -0.986452
UMUARAMA            local            -0.972794
UNIÃO DA VITÓRIA    local            -0.991076
ASSIS CHATEAUBRIAND global           -0.964858
ASTORGA             global           -0.866449
BARRACÃO            global           -0.909844
CAMPO LARGO         global           -0.947309
CAPANEMA            global           -0.952214
CASCAVEL            global           -0.910000
CORONEL VIVIDA      global           -0.966617
CURITIBA            global           -1.301346
FOZ DO IGUAÇU       global           -0.898596
GOIOERÊ             global           -0.876188
IRATI               global           -0.857560
IVAIPORÃ            global           -0.897754
JACAREZINHO         global           -0.965783
JAGUARIAÍVA         global           -0.867103
LONDRINA - CENTRO   global           -1.332856
PALMAS              global           -1.029019
PARANAGUÁ           global           -0.888948
PARANAVAÍ           global           -0.899532
PINHAIS             global           -0.948257
PITANGA             global           -0.929521
QUEDAS DO IGUAÇU    global           -0.959179
TELÊMACO BORBA      global           -0.869959
UMUARAMA            global           -0.870266
UNIÃO DA VITÓRIA    global           -0.862347



## Treinamento Local

In [22]:
for horizonte in HORIZONTES:
    df_treino = dfs_treino[horizonte]
    for campus, dados_teste in dfs_teste[horizonte].sort_values("DATA").groupby("CAMPUS"):
        dados_teste = dados_teste.set_index('DATA')
        df_previsoes = pd.DataFrame(columns=MODELOS, index=dados_teste.index)

        for nome_modelo in MODELOS:
            # Treina o modelo com os dados do campus atual
            dados_treino = df_treino[df_treino["CAMPUS"] == campus]
            modelo = treino(get_modelo(nome_modelo, tipo_treino="local", campus=campus), dados_treino, df_features)

            # Testa o modelo com os dados do campus atual
            previsoes = teste(modelo, dados_treino, dados_teste, df_features, horizonte)
            df_previsoes[[nome_modelo]] = scalers[campus].inverse_transform(previsoes[["CONSUMO PREVISTO"]])

        os.makedirs(f"resultados/regressão - local/{horizonte} meses", exist_ok=True)
        df_previsoes.to_csv(f"resultados/regressão - local/{horizonte} meses/PREVISÕES {horizonte}M - {campus}.csv",
                            sep=";", decimal=".", header=True,
                            index=True)

## Treinamento Global

In [23]:

for horizonte in HORIZONTES:
    df_treino = dfs_treino[horizonte]
    for campus, dados_teste in dfs_teste[horizonte].sort_values("DATA").groupby("CAMPUS"):
        dados_teste = dados_teste.set_index('DATA')
        df_previsoes = pd.DataFrame(columns=MODELOS, index=dados_teste.index)

        for nome_modelo in MODELOS:
            # Treina o modelo com os dados de todos os campi
            modelo = treino(get_modelo(nome_modelo, tipo_treino="global", campus=campus), df_treino, df_features)

            # Testa o modelo com os dados do campus atual
            previsoes = teste(modelo, df_treino[df_treino["CAMPUS"] == campus], dados_teste, df_features, horizonte)
            df_previsoes[[nome_modelo]] = scalers[campus].inverse_transform(previsoes[["CONSUMO PREVISTO"]])

        os.makedirs(f"resultados/regressão - global/{horizonte} meses", exist_ok=True)
        df_previsoes.to_csv(f"resultados/regressão - global/{horizonte} meses/PREVISÕES {horizonte}M - {campus}.csv",
                            sep=";", decimal=".",
                            index=True)

# Análise dos Resultados

In [24]:
def ts_comparacao(campus, valor_real, valores_previstos, erros, horizonte):
    valor_real = valor_real.tail(horizonte)
    plt.figure(figsize=(12, 4.5))
    plt.rcParams['xtick.labelsize'] = 13
    plt.rcParams['ytick.labelsize'] = 14
    plt.rcParams.update({'font.size': 12})
    plt.rcParams['axes.prop_cycle'] = plt.cycler(
        color=["blue", "green", "darkgoldenrod", colors.red_rgb, "purple", "cyan", "slategrey", "coral"])

    for nome_modelo in valores_previstos.columns:
        plt.plot(valores_previstos[nome_modelo],
                 label=f"{nome_modelo} (RRMSE: {erros.loc[nome_modelo]["RRMSE"]:.2%} - MAPE: {erros.loc[nome_modelo]["MAPE"]:.2%})")

    plt.plot(valor_real["CONSUMO"], label=f"CONSUMO REAL - {campus}", color="black")

    plt.xlabel('Mês')
    plt.ylabel('Consumo (KWh)')

    ax = plt.gca()
    ax.set_facecolor('white')

    plt.grid(True, color='grey', linestyle="--", linewidth=0.5)
    plt.legend(facecolor='white')

    return plt


def medidas_desempenho(valor_real, valores_previstos, horizonte):
    df_desempenho = pd.DataFrame(columns=["MAPE", "RRMSE"], index=valores_previstos.columns)

    for nome_modelo in valores_previstos.columns:
        df_desempenho.loc[nome_modelo] = [
            mape(valor_real["CONSUMO"].tail(horizonte), valores_previstos[nome_modelo].tail(horizonte)),
            calcular_rrmse(valor_real["CONSUMO"].tail(horizonte), valores_previstos[nome_modelo].tail(horizonte)),
        ]

    return df_desempenho

## Treinamento Local

In [28]:
df_real = pd.read_csv("./dados/dados_tratados.csv", sep=';', decimal='.')

for horizonte in HORIZONTES:
    df_RRMSE = pd.DataFrame(columns=MODELOS, index=df_real["CAMPUS"].unique())
    df_MAPE = pd.DataFrame(columns=MODELOS, index=df_real["CAMPUS"].unique())

    for campus, dados in df_real.sort_values("DATA").groupby("CAMPUS"):
        try:
            consumo_previsto = pd.read_csv(
                f"resultados/regressão - local/{horizonte} meses/PREVISÕES {horizonte}M - {campus}.csv",
                sep=";", decimal=".", header=0)
        except Exception as e:
            continue

        consumo_previsto["DATA"] = pd.to_datetime(consumo_previsto["DATA"])
        consumo_previsto = consumo_previsto.set_index("DATA")

        dados["DATA"] = pd.to_datetime(dados["DATA"])
        dados = dados.set_index("DATA")

        df_desempenho = medidas_desempenho(dados, consumo_previsto, horizonte)
        df_RRMSE.loc[campus] = df_desempenho["RRMSE"]
        df_MAPE.loc[campus] = df_desempenho["MAPE"]

        plt = ts_comparacao(campus, dados, consumo_previsto, df_desempenho, horizonte)

        df_desempenho.to_csv(f"resultados/regressão - local/{horizonte} meses/RRMSE {horizonte}M {campus}.csv",
                             sep=";", decimal=".", index=True)
        plt.savefig(f"resultados/regressão - local/{horizonte} meses/PREVISÕES {horizonte}M {campus}.png",
                    bbox_inches='tight')
        plt.close()

    df_RRMSE = df_RRMSE.add_suffix(" RRMSE")
    df_MAPE = df_MAPE.add_suffix(" MAPE")

    pior_RRMSE = (df_RRMSE.eq(df_RRMSE.max(axis=1), axis=0).sum(axis=0))
    melhor_RRMSE = (df_RRMSE.eq(df_RRMSE.min(axis=1), axis=0).sum(axis=0))

    pior_MAPE = (df_MAPE.eq(df_MAPE.max(axis=1), axis=0).sum(axis=0))
    melhor_MAPE = (df_MAPE.eq(df_MAPE.min(axis=1), axis=0).sum(axis=0))

    df_medias = pd.concat([df_RRMSE, df_MAPE], axis=1)
    df_medias.loc["MÉDIAS"] = df_medias.mean()

    df_medias.loc["MELHOR"] = pd.concat([melhor_RRMSE, melhor_MAPE], axis=0)
    df_medias.loc["PIOR"] = pd.concat([pior_RRMSE, pior_MAPE], axis=0)
    df_medias.loc["SCORE (MELHOR - PIOR)"] = pd.concat([melhor_RRMSE - pior_RRMSE, melhor_MAPE - pior_MAPE], axis=0)

    df_medias.to_csv(f"resultados/regressão - local/MÉDIAS ERROS {horizonte}M.csv", sep=";", decimal=".", index=True)
    display(df_medias)

,ESN RRMSE,MLP RRMSE,RF RRMSE,XGBoost RRMSE,WSB RRMSE,ESN MAPE,MLP MAPE,RF MAPE,XGBoost MAPE,WSB MAPE
ASSIS CHATEAUBRIAND,0.311359,0.12425,0.296678,0.384678,0.28787,0.259414,0.064378,0.219504,0.289052,0.221084
ASTORGA,0.326683,0.278516,0.298948,0.334858,0.282408,0.272433,0.273608,0.27509,0.29229,0.257383
BARRACÃO,0.10952,0.159638,0.135852,0.272083,0.151288,0.096757,0.158585,0.135869,0.269534,0.151525
CAMPO LARGO,0.314383,0.286582,0.173849,0.306255,0.263246,0.275375,0.284823,0.169982,0.297039,0.249638
CAPANEMA,0.422843,0.203984,0.230291,0.166305,0.210543,0.315073,0.10328,0.171482,0.137143,0.128284
CASCAVEL,0.282968,0.178718,0.245105,0.265865,0.256957,0.253321,0.160683,0.177289,0.203063,0.198022
CORONEL VIVIDA,0.293099,0.239361,0.19786,0.218547,0.229331,0.22363,0.231081,0.16801,0.20223,0.213341
CURITIBA,0.962509,0.220101,0.167784,0.261969,0.085938,0.901734,0.133404,0.165749,0.245824,0.076106
FOZ DO IGUAÇU,0.222286,0.285499,0.118387,0.21132,0.205121,0.201441,0.247414,0.112985,0.203257,0.16135
GOIOERÊ,0.306091,0.18162,0.112599,0.281516,0.068387,0.289228,0.145535,0.099313,0.199324,0.064099
IRATI,0.236625,0.237654,0.210193,0.219921,0.227752,0.185424,0.232134,0.190439,0.142679,0.192921
IVAIPORÃ,0.298911,0.192786,0.272048,0.300932,0.237414,0.263785,0.153534,0.202431,0.251651,0.188786
JACAREZINHO,0.476111,0.332657,0.260311,0.324868,0.306659,0.47998,0.335267,0.241769,0.25926,0.263676
JAGUARIAÍVA,0.347135,0.209788,0.218228,0.121706,0.15682,0.297708,0.206329,0.194126,0.09023,0.133047
LONDRINA - CENTRO,0.289412,0.149782,0.14681,0.225829,0.178107,0.288838,0.131266,0.13403,0.197722,0.160102
PALMAS,0.277531,0.247778,0.155626,0.225705,0.237795,0.271965,0.246387,0.15291,0.215292,0.234545
PARANAGUÁ,0.222485,0.283925,0.230925,0.297217,0.234907,0.151762,0.236421,0.176995,0.198377,0.177916
PARANAVAÍ,0.487707,0.435699,0.289728,0.310424,0.359615,0.371627,0.393076,0.247191,0.223771,0.27134
PINHAIS,0.299307,0.199,0.084379,0.101356,0.132629,0.270524,0.165425,0.082674,0.1008,0.130657
PITANGA,0.248506,0.252643,0.19424,0.191836,0.189808,0.240657,0.192086,0.177583,0.183117,0.177948
QUEDAS DO IGUAÇU,0.235727,0.11967,0.144467,0.238389,0.18638,0.23536,0.096615,0.132513,0.199052,0.161943
TELÊMACO BORBA,0.433792,0.236882,0.235091,0.278209,0.250428,0.378627,0.240054,0.184404,0.213788,0.192696
UMUARAMA,0.287127,0.274121,0.225062,0.272279,0.26471,0.262333,0.281312,0.225032,0.255108,0.251839
UNIÃO DA VITÓRIA,0.350557,0.218305,0.272916,0.32642,0.279058,0.342018,0.170035,0.253249,0.262768,0.24585
MÉDIAS,0.335111,0.231207,0.204891,0.25577,0.220132,0.297042,0.203447,0.178776,0.213849,0.187671
MELHOR,2,6,11,2,3,2,7,9,3,3
PIOR,15,3,0,6,0,14,6,0,4,0
SCORE (MELHOR - PIOR),-13,3,11,-4,3,-12,1,9,-1,3

,ESN RRMSE,MLP RRMSE,RF RRMSE,XGBoost RRMSE,WSB RRMSE,ESN MAPE,MLP MAPE,RF MAPE,XGBoost MAPE,WSB MAPE
ASSIS CHATEAUBRIAND,0.32826,0.52359,0.420644,0.42222,0.390806,0.25045,0.757365,0.511374,0.479986,0.469771
ASTORGA,0.307834,0.284013,0.288267,0.300552,0.265609,0.222226,0.267246,0.242436,0.222603,0.200764
BARRACÃO,0.250062,0.209844,0.198753,0.242066,0.214467,0.208184,0.209669,0.181716,0.221636,0.197388
CAMPO LARGO,0.467923,0.425668,0.363527,0.388361,0.369557,0.601344,0.542792,0.402035,0.459732,0.454286
CAPANEMA,0.508555,0.451082,0.401643,0.338276,0.339324,0.50463,0.623115,0.503296,0.412497,0.391999
CASCAVEL,0.47233,0.419661,0.365115,0.329403,0.319426,0.591357,0.466084,0.380758,0.382373,0.365445
CORONEL VIVIDA,0.245431,0.277802,0.217247,0.205905,0.194405,0.206578,0.282892,0.167997,0.152297,0.144124
CURITIBA,0.591001,0.342616,0.312017,0.288538,0.243009,0.29812,0.344478,0.338032,0.289919,0.259644
FOZ DO IGUAÇU,0.450966,0.4306,0.432367,0.338752,0.339184,0.421524,0.416376,0.43472,0.330228,0.319812
GOIOERÊ,0.469175,0.514052,0.350443,0.53874,0.517599,0.446817,0.542512,0.346408,0.477793,0.446678
IRATI,0.336667,0.335483,0.271787,0.315994,0.308219,0.321601,0.374231,0.292185,0.285126,0.284668
IVAIPORÃ,0.357467,0.2902,0.286983,0.233197,0.213871,0.360776,0.281085,0.261833,0.179113,0.171005
JACAREZINHO,0.521857,0.405058,0.333273,0.365213,0.347893,0.522424,0.452708,0.35665,0.364515,0.345886
JAGUARIAÍVA,0.430226,0.273637,0.257422,0.253485,0.260088,0.374611,0.303649,0.286917,0.252148,0.271907
LONDRINA - CENTRO,0.537448,0.307275,0.344641,0.251461,0.245875,0.496006,0.29196,0.313904,0.258839,0.247522
PALMAS,0.415607,0.226573,0.185146,0.244932,0.243131,0.394329,0.210453,0.141178,0.186974,0.185055
PARANAGUÁ,0.235839,0.279304,0.219131,0.249254,0.215636,0.197032,0.245085,0.160161,0.146499,0.138415
PARANAVAÍ,0.626508,0.507822,0.402649,0.350999,0.373746,0.461283,0.56907,0.463991,0.341156,0.371744
PINHAIS,0.360011,0.461685,0.210079,0.19851,0.195432,0.349672,0.429091,0.188494,0.181342,0.18215
PITANGA,0.366851,0.329038,0.302219,0.311014,0.30468,0.400378,0.3451,0.334184,0.331862,0.327954
QUEDAS DO IGUAÇU,0.344229,0.35313,0.228914,0.270204,0.257895,0.292608,0.350492,0.227343,0.277873,0.258719
TELÊMACO BORBA,0.377218,0.319757,0.322992,0.284437,0.282241,0.332262,0.36543,0.338894,0.266498,0.265535
UMUARAMA,0.361506,0.458986,0.39442,0.448104,0.434221,0.365313,0.613696,0.470882,0.573203,0.560993
UNIÃO DA VITÓRIA,0.48983,0.356926,0.365353,0.346215,0.351291,0.50182,0.360283,0.394901,0.351919,0.365282
MÉDIAS,0.410533,0.365992,0.31146,0.31316,0.30115,0.380056,0.401869,0.322512,0.309422,0.301114
MELHOR,2,0,8,5,9,2,0,5,4,13
PIOR,17,6,0,1,0,9,13,1,1,0
SCORE (MELHOR - PIOR),-15,-6,8,4,9,-7,-13,4,3,13

,ESN RRMSE,MLP RRMSE,RF RRMSE,XGBoost RRMSE,WSB RRMSE,ESN MAPE,MLP MAPE,RF MAPE,XGBoost MAPE,WSB MAPE
ASSIS CHATEAUBRIAND,0.280578,0.398155,0.36148,0.345205,0.344896,0.178217,0.551513,0.41961,0.41411,0.419487
ASTORGA,0.477217,0.308458,0.306776,0.334848,0.327267,0.430907,0.236664,0.228922,0.255418,0.245007
BARRACÃO,0.288687,0.229966,0.295104,0.27954,0.273175,0.233853,0.21752,0.26805,0.242562,0.240372
CAMPO LARGO,0.365603,0.334673,0.335989,0.326037,0.311579,0.358701,0.378977,0.355507,0.320603,0.328726
CAPANEMA,0.535447,0.431023,0.395956,0.340894,0.364174,0.470756,0.550737,0.436529,0.365215,0.396548
CASCAVEL,0.273705,0.298589,0.326426,0.283239,0.273274,0.283747,0.285663,0.328,0.256836,0.256368
CORONEL VIVIDA,0.345348,0.34397,0.267654,0.239236,0.254817,0.304481,0.379106,0.287886,0.250438,0.268652
CURITIBA,0.841661,0.393413,0.295968,0.354607,0.31337,0.668006,0.250875,0.264717,0.309176,0.260667
FOZ DO IGUAÇU,0.385475,0.512756,0.438348,0.485188,0.476748,0.423062,0.566678,0.510157,0.518693,0.52358
GOIOERÊ,0.25546,0.266759,0.304176,0.277809,0.269538,0.272904,0.298071,0.276366,0.281362,0.262461
IRATI,0.368788,0.31584,0.337238,0.393874,0.367529,0.303879,0.289417,0.272024,0.269019,0.258873
IVAIPORÃ,10.280054,0.318144,0.306779,0.285897,0.284644,10.408902,0.270548,0.240059,0.192295,0.201135
JACAREZINHO,173.726062,0.341559,0.374992,0.392457,0.381017,199.817855,0.298549,0.332827,0.362467,0.350437
JAGUARIAÍVA,0.367067,0.275376,0.238203,0.272849,0.264559,0.290542,0.238439,0.229941,0.234254,0.228067
LONDRINA - CENTRO,0.687454,0.212901,0.273305,0.285448,0.272017,0.729191,0.198489,0.258115,0.23406,0.243157
PALMAS,0.839734,0.249687,0.232945,0.273831,0.252437,0.866119,0.23279,0.210389,0.264424,0.252158
PARANAGUÁ,0.236248,0.216953,0.227111,0.261347,0.24763,0.181951,0.198017,0.173009,0.189006,0.189802
PARANAVAÍ,0.424595,0.386512,0.385864,0.385577,0.385333,0.376534,0.451139,0.424467,0.394641,0.404206
PINHAIS,0.34269,0.364163,0.210812,0.227991,0.223897,0.247883,0.336123,0.199617,0.206864,0.204267
PITANGA,0.262046,0.255861,0.291269,0.326883,0.301795,0.232519,0.228442,0.24618,0.299658,0.278537
QUEDAS DO IGUAÇU,0.342789,0.328021,0.249307,0.249681,0.248304,0.332665,0.312746,0.223424,0.228112,0.232614
TELÊMACO BORBA,0.288064,0.257202,0.264973,0.238255,0.232278,0.228816,0.276687,0.277051,0.22152,0.221218
UMUARAMA,0.279215,0.301097,0.325063,0.336601,0.337738,0.235759,0.376732,0.363115,0.37991,0.386965
UNIÃO DA VITÓRIA,0.375713,0.292698,0.26002,0.239502,0.257108,0.34624,0.251394,0.252795,0.215177,0.227526
MÉDIAS,8.036237,0.318074,0.304407,0.309867,0.302713,9.092645,0.319805,0.294948,0.287742,0.286701
MELHOR,4,6,5,3,6,4,5,5,5,5
PIOR,14,3,3,3,1,10,9,3,1,1
SCORE (MELHOR - PIOR),-10,3,2,0,5,-6,-4,2,4,4

## Treinamento Global

In [27]:
df_real = pd.read_csv("./dados/dados_tratados.csv", sep=';', decimal='.')

for horizonte in HORIZONTES:

    df_RRMSE = pd.DataFrame(columns=MODELOS, index=df_real["CAMPUS"].unique())
    df_MAPE = pd.DataFrame(columns=MODELOS, index=df_real["CAMPUS"].unique())

    for campus, dados in df_real.sort_values("DATA").groupby("CAMPUS"):
        try:
            consumo_previsto = pd.read_csv(
                f"resultados/regressão - global/{horizonte} meses/PREVISÕES {horizonte}M - {campus}.csv",
                sep=";", decimal=".", header=0)
        except Exception as e:
            continue

        consumo_previsto["DATA"] = pd.to_datetime(consumo_previsto["DATA"])
        consumo_previsto = consumo_previsto.set_index("DATA")

        dados["DATA"] = pd.to_datetime(dados["DATA"])
        dados = dados.set_index("DATA")

        df_desempenho = medidas_desempenho(dados, consumo_previsto, horizonte)
        df_RRMSE.loc[campus] = df_desempenho["RRMSE"]
        df_MAPE.loc[campus] = df_desempenho["MAPE"]

        plt = ts_comparacao(campus, dados, consumo_previsto, df_desempenho, horizonte)

        df_desempenho.to_csv(f"resultados/regressão - global/{horizonte} meses/RRMSE {horizonte}M {campus}.csv",
                             sep=";", decimal=".", index=True)
        plt.savefig(f"resultados/regressão - global/{horizonte} meses/PREVISÕES {horizonte}M {campus}.png",
                    bbox_inches='tight')
        plt.close()

    df_RRMSE = df_RRMSE.add_suffix(" RRMSE")
    df_MAPE = df_MAPE.add_suffix(" MAPE")

    pior_RRMSE = (df_RRMSE.eq(df_RRMSE.max(axis=1), axis=0).sum(axis=0))
    melhor_RRMSE = (df_RRMSE.eq(df_RRMSE.min(axis=1), axis=0).sum(axis=0))

    pior_MAPE = (df_MAPE.eq(df_MAPE.max(axis=1), axis=0).sum(axis=0))
    melhor_MAPE = (df_MAPE.eq(df_MAPE.min(axis=1), axis=0).sum(axis=0))

    df_medias = pd.concat([df_RRMSE, df_MAPE], axis=1)
    df_medias.loc["MÉDIAS"] = df_medias.mean()

    df_medias.loc["MELHOR"] = pd.concat([melhor_RRMSE, melhor_MAPE], axis=0)
    df_medias.loc["PIOR"] = pd.concat([pior_RRMSE, pior_MAPE], axis=0)
    df_medias.loc["SCORE (MELHOR - PIOR)"] = pd.concat([melhor_RRMSE - pior_RRMSE, melhor_MAPE - pior_MAPE], axis=0)

    df_medias.to_csv(f"resultados/regressão - global/MÉDIAS ERROS {horizonte}M.csv", sep=";", decimal=".", index=True)
    display(df_medias)

,ESN RRMSE,MLP RRMSE,RF RRMSE,XGBoost RRMSE,WSB RRMSE,ESN MAPE,MLP MAPE,RF MAPE,XGBoost MAPE,WSB MAPE
ASSIS CHATEAUBRIAND,0.335021,0.52028,0.241681,0.310252,0.30808,0.320783,0.415469,0.204475,0.210689,0.232188
ASTORGA,0.239765,0.400109,0.183562,0.11608,0.211597,0.219098,0.388658,0.176063,0.093383,0.197268
BARRACÃO,0.143302,0.255247,0.150445,0.167824,0.158387,0.125761,0.247998,0.139153,0.154716,0.142712
CAMPO LARGO,0.214925,0.346374,0.247012,0.248021,0.260631,0.184126,0.342332,0.219828,0.244664,0.245355
CAPANEMA,0.344694,0.485142,0.291509,0.278738,0.309365,0.332013,0.382279,0.261259,0.177098,0.252029
CASCAVEL,0.233249,0.370364,0.213974,0.254905,0.241626,0.169461,0.343652,0.188028,0.232148,0.216771
CORONEL VIVIDA,0.201665,0.29845,0.203325,0.222105,0.214436,0.169635,0.27545,0.178974,0.195599,0.186989
CURITIBA,0.321913,0.30471,0.057306,0.115496,0.206465,0.305627,0.297917,0.053383,0.107602,0.17333
FOZ DO IGUAÇU,0.237318,0.252213,0.111688,0.089633,0.124756,0.225089,0.235992,0.102689,0.075077,0.123002
GOIOERÊ,0.465857,0.142725,0.185727,0.263042,0.231487,0.438196,0.14076,0.193288,0.262948,0.226122
IRATI,0.170384,0.306555,0.129981,0.169472,0.16699,0.147688,0.30346,0.125948,0.146712,0.163941
IVAIPORÃ,0.247139,0.373234,0.131322,0.120184,0.188759,0.212975,0.323918,0.11601,0.121858,0.162477
JACAREZINHO,0.234526,0.395612,0.148339,0.162289,0.181216,0.182052,0.356412,0.129705,0.139331,0.159943
JAGUARIAÍVA,0.206169,0.343887,0.181159,0.181245,0.201683,0.174492,0.334634,0.164322,0.154982,0.185566
LONDRINA - CENTRO,0.177853,0.274817,0.101994,0.1049,0.121269,0.169165,0.201488,0.091922,0.106857,0.109544
PALMAS,0.096398,0.29575,0.096545,0.130608,0.123756,0.089936,0.294106,0.091009,0.130431,0.123038
PARANAGUÁ,0.227317,0.376212,0.145129,0.142958,0.195144,0.139657,0.335164,0.110808,0.123621,0.146734
PARANAVAÍ,0.356535,0.447748,0.304446,0.335844,0.339018,0.304618,0.356346,0.222683,0.235194,0.238994
PINHAIS,0.214381,0.074381,0.070166,0.076049,0.055292,0.196822,0.07216,0.060961,0.075782,0.038294
PITANGA,0.169566,0.330579,0.166328,0.181528,0.17247,0.145038,0.327052,0.12374,0.163648,0.141764
QUEDAS DO IGUAÇU,0.190941,0.250527,0.139345,0.139296,0.149592,0.182527,0.224222,0.139133,0.133019,0.149729
TELÊMACO BORBA,0.224145,0.313674,0.183009,0.190364,0.21311,0.201334,0.27849,0.152202,0.166055,0.164577
UMUARAMA,0.268334,0.398317,0.14474,0.153536,0.208705,0.197792,0.33744,0.123193,0.124585,0.161901
UNIÃO DA VITÓRIA,0.135543,0.245511,0.197251,0.219677,0.197435,0.117952,0.24192,0.165212,0.19064,0.178462
MÉDIAS,0.235706,0.325101,0.167749,0.182252,0.19922,0.206327,0.294055,0.14725,0.156943,0.171697
MELHOR,5,1,11,6,1,6,1,11,5,1
PIOR,3,21,0,0,0,3,21,0,0,0
SCORE (MELHOR - PIOR),2,-20,11,6,1,3,-20,11,5,1

,ESN RRMSE,MLP RRMSE,RF RRMSE,XGBoost RRMSE,WSB RRMSE,ESN MAPE,MLP MAPE,RF MAPE,XGBoost MAPE,WSB MAPE
ASSIS CHATEAUBRIAND,0.455575,0.563616,0.531734,0.40938,0.408036,0.480224,0.772425,0.744592,0.541963,0.463381
ASTORGA,0.228303,0.192581,0.193867,0.127091,0.191994,0.188281,0.183534,0.168523,0.117226,0.161906
BARRACÃO,0.21964,0.201621,0.237855,0.179884,0.211702,0.182349,0.188269,0.194322,0.152587,0.175596
CAMPO LARGO,0.276241,0.347924,0.31567,0.359276,0.271879,0.319383,0.447986,0.40275,0.445261,0.322454
CAPANEMA,0.408605,0.516813,0.467003,0.453281,0.3929,0.489924,0.678008,0.647627,0.584114,0.495529
CASCAVEL,0.291019,0.35645,0.332701,0.378977,0.283268,0.295189,0.402957,0.405603,0.429562,0.304275
CORONEL VIVIDA,0.230479,0.214701,0.256904,0.223953,0.219789,0.179715,0.21883,0.204143,0.169478,0.171944
CURITIBA,0.287094,0.545697,0.211593,0.257673,0.24725,0.26334,0.632672,0.217248,0.281225,0.235444
FOZ DO IGUAÇU,0.256414,0.627122,0.348797,0.317584,0.246699,0.230079,0.632343,0.307016,0.259493,0.224994
GOIOERÊ,0.445886,0.654663,0.525382,0.536829,0.455773,0.356874,0.677914,0.507368,0.502124,0.386679
IRATI,0.290742,0.292649,0.318916,0.295254,0.272895,0.263912,0.296006,0.317047,0.292704,0.237203
IVAIPORÃ,0.27049,0.294385,0.249618,0.200689,0.235565,0.235521,0.288076,0.259567,0.194459,0.220948
JACAREZINHO,0.293208,0.411226,0.348075,0.341576,0.275273,0.330944,0.487784,0.384767,0.380488,0.30082
JAGUARIAÍVA,0.296104,0.241938,0.279544,0.266935,0.280042,0.246881,0.241519,0.218239,0.240326,0.227702
LONDRINA - CENTRO,0.31389,0.616935,0.418123,0.396288,0.32744,0.271157,0.658176,0.382828,0.388977,0.297745
PALMAS,0.181462,0.142499,0.212755,0.203056,0.17947,0.111401,0.119393,0.157,0.137625,0.115178
PARANAGUÁ,0.258821,0.321336,0.285183,0.23252,0.231169,0.203872,0.318756,0.250243,0.214745,0.184127
PARANAVAÍ,0.375347,0.4363,0.457755,0.469561,0.346711,0.366153,0.545201,0.534962,0.53604,0.351686
PINHAIS,0.192874,0.324753,0.261612,0.258526,0.187207,0.180681,0.311979,0.252198,0.248048,0.175808
PITANGA,0.236208,0.237556,0.241967,0.218772,0.219514,0.229747,0.243226,0.247001,0.230716,0.210847
QUEDAS DO IGUAÇU,0.239287,0.260211,0.264184,0.258565,0.233825,0.196448,0.244231,0.234217,0.242569,0.196393
TELÊMACO BORBA,0.279898,0.266127,0.260204,0.261992,0.259438,0.263977,0.294957,0.249994,0.259126,0.247933
UMUARAMA,0.451945,0.539468,0.47454,0.408708,0.42199,0.423948,0.707547,0.600808,0.439583,0.422787
UNIÃO DA VITÓRIA,0.314342,0.298209,0.335879,0.312123,0.304338,0.226247,0.272935,0.255312,0.271702,0.203529
MÉDIAS,0.295578,0.371032,0.326244,0.307021,0.27934,0.272344,0.41103,0.339307,0.315006,0.263954
MELHOR,2,4,1,5,12,6,0,2,4,12
PIOR,3,11,7,3,0,2,17,4,1,0
SCORE (MELHOR - PIOR),-1,-7,-6,2,12,4,-17,-2,3,12

,ESN RRMSE,MLP RRMSE,RF RRMSE,XGBoost RRMSE,WSB RRMSE,ESN MAPE,MLP MAPE,RF MAPE,XGBoost MAPE,WSB MAPE
ASSIS CHATEAUBRIAND,0.383148,0.506564,0.385431,0.342546,0.362573,0.368745,0.697377,0.495534,0.437677,0.41044
ASTORGA,0.245551,0.246899,0.211425,0.194686,0.215953,0.211714,0.232863,0.18068,0.15165,0.188187
BARRACÃO,0.173661,0.138861,0.210286,0.19232,0.16164,0.129046,0.120696,0.185361,0.16917,0.126557
CAMPO LARGO,0.267975,0.404535,0.293833,0.317331,0.275311,0.296047,0.491012,0.332771,0.343311,0.319032
CAPANEMA,0.352819,0.539397,0.409939,0.430239,0.364272,0.351762,0.676248,0.461265,0.496933,0.402251
CASCAVEL,0.26059,0.332521,0.260665,0.274501,0.261245,0.245421,0.371156,0.296631,0.295241,0.273319
CORONEL VIVIDA,0.278768,0.336191,0.299007,0.269459,0.271586,0.246694,0.391226,0.259948,0.238781,0.245954
CURITIBA,0.259464,0.394579,0.299062,0.320178,0.264983,0.22737,0.412633,0.30465,0.249723,0.235209
FOZ DO IGUAÇU,0.404487,0.691073,0.43975,0.409392,0.408254,0.415203,0.805284,0.4235,0.359564,0.405657
GOIOERÊ,0.266711,0.35742,0.285289,0.270382,0.272007,0.250127,0.423674,0.30849,0.277902,0.272567
IRATI,0.257275,0.245582,0.229581,0.243938,0.240881,0.212513,0.261622,0.204407,0.19454,0.1912
IVAIPORÃ,0.253824,0.301374,0.205922,0.162194,0.212365,0.191227,0.300273,0.193106,0.142071,0.175349
JACAREZINHO,0.295862,0.353974,0.305106,0.302128,0.292001,0.303261,0.418553,0.328291,0.317104,0.309308
JAGUARIAÍVA,0.246397,0.2097,0.233978,0.195708,0.219054,0.191207,0.197736,0.174968,0.171326,0.172838
LONDRINA - CENTRO,0.207242,0.359133,0.269493,0.272588,0.228887,0.170188,0.387506,0.274401,0.230539,0.209663
PALMAS,0.23545,0.34513,0.2751,0.261569,0.248387,0.205853,0.360469,0.234723,0.244345,0.223307
PARANAGUÁ,0.209668,0.229995,0.201074,0.1734,0.187988,0.16788,0.215386,0.17899,0.167041,0.150535
PARANAVAÍ,0.365694,0.49727,0.374821,0.423902,0.372895,0.382154,0.623452,0.418667,0.472559,0.410415
PINHAIS,0.185151,0.316961,0.209446,0.220185,0.194451,0.165665,0.303576,0.196639,0.199145,0.183668
PITANGA,0.221305,0.230533,0.215945,0.187899,0.199594,0.182264,0.225369,0.199105,0.156018,0.168259
QUEDAS DO IGUAÇU,0.24509,0.31326,0.246102,0.210709,0.237615,0.201015,0.301703,0.193609,0.169154,0.200593
TELÊMACO BORBA,0.237956,0.25205,0.214864,0.211495,0.21913,0.201809,0.269919,0.202821,0.199338,0.198224
UMUARAMA,0.311718,0.358049,0.310644,0.299457,0.292234,0.296165,0.488513,0.363535,0.323939,0.302028
UNIÃO DA VITÓRIA,0.259137,0.235398,0.273379,0.244311,0.248899,0.187094,0.208942,0.213979,0.198508,0.174141
MÉDIAS,0.267706,0.341519,0.277506,0.267938,0.260509,0.241684,0.382716,0.276086,0.258566,0.247863
MELHOR,10,2,1,9,2,12,1,0,7,4
PIOR,2,20,2,0,0,0,22,2,0,0
SCORE (MELHOR - PIOR),8,-18,-1,9,2,12,-21,-2,7,4